<?php
/**
 * Class was generated by WSDL2PHP tool
 * Timestamp: 1364826896
 *
 * PHP version 5
 *
 * @category Tools
 * @package  WSDL
 * @author   Andrey Filippov <afi.work@gmail.com>
 * @license  %license%
 * @link     https://solo-framework-lib.googlecode.com
 */

namespace Moneta;

/*REQUIRE_DATATYPES*/

class MonetaWebServiceConnector
{
	/**
	 * Mapping PHP classes and types from a WSDL
	 * Key - type defined in WSDL, value - PHP class name
	 * To avoid conflicts with another classes we have to add prefix for generated data types
	 */
	//private static $classmap = array(/*CLASSMAP*/);

	/**
	 * SoapClient instance
	 *
	 * @var \SoapClient
	 */
	protected $client = null;

	/**
	 * An array of headers to be sent along with the SOAP request
	 *
	 * @var array
	 */
	protected $inputHeaders = null;

	/**
	 * If supplied, this array will be filled with the headers from the SOAP response
	 *
	 * @var array
	 */
	protected $outputHeaders = null;


	/**
	 * Constructor
	 *
	 * @param string $wsdl Path or URL to WSDL file
	 * @param array $options Options like SoapClient->__construct()
	 *
	 * @return \WebServiceConnector
	 */
	function __construct($wsdl, $options = null)
	{
//		foreach(self::$classmap as $key => $value)
//			if(!isset($options["classmap"][$key]))
//				$options["classmap"][$key] = $value;

		if($options === null)
			$options = array();

		$this->client = new \SoapClient($wsdl, $options);
	}

	// Block of generated methods
	
	/**
	 * 
	 *
	 * @param AuthoriseTransactionBatchRequest $request
	 *
	 * @return AuthoriseTransactionBatchResponse
	 */
	public function AuthoriseTransactionBatch(AuthoriseTransactionBatchRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param string $request
	 *
	 * @return FindAccountByAliasResponse
	 */
	public function FindAccountByAlias( $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param ForecastTransactionRequest $request
	 *
	 * @return ForecastTransactionResponse
	 */
	public function ForecastTransaction(ForecastTransactionRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param TransferBatchRequest $request
	 *
	 * @return TransferBatchResponse
	 */
	public function TransferBatch(TransferBatchRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param CreateProfileDocumentRequest $request
	 *
	 * @return CreateProfileDocumentResponse
	 */
	public function CreateProfileDocument(CreateProfileDocumentRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param GetTurnoverListRequest $request
	 *
	 * @return GetTurnoverListResponse
	 */
	public function GetTurnoverList(GetTurnoverListRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param PaymentRequest $request
	 *
	 * @return PaymentResponse
	 */
	public function Payment(PaymentRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param ConfirmTransactionBatchRequest $request
	 *
	 * @return ConfirmTransactionBatchResponse
	 */
	public function ConfirmTransactionBatch(ConfirmTransactionBatchRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param SaveAccountRelationRequest $request
	 *
	 * @return SaveAccountRelationResponse
	 */
	public function SaveAccountRelation(SaveAccountRelationRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param FindProfileDocumentFilesRequest $request
	 *
	 * @return FindProfileDocumentFilesResponse
	 */
	public function FindProfileDocumentFiles(FindProfileDocumentFilesRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param AuthoriseTransactionRequest $request
	 *
	 * @return AuthoriseTransactionResponse
	 */
	public function AuthoriseTransaction(AuthoriseTransactionRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param VerifyTransferRequest $request
	 *
	 * @return VerifyTransferResponse
	 */
	public function VerifyTransfer(VerifyTransferRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param CancelTransactionBatchRequest $request
	 *
	 * @return CancelTransactionBatchResponse
	 */
	public function CancelTransactionBatch(CancelTransactionBatchRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param ConfirmTransactionRequest $request
	 *
	 * @return ConfirmTransactionResponse
	 */
	public function ConfirmTransaction(ConfirmTransactionRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param FindAccountsListRequest $request
	 *
	 * @return FindAccountsListResponse
	 */
	public function FindAccountsList(FindAccountsListRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param FindAccountRelationsRequest $request
	 *
	 * @return FindAccountRelationsResponse
	 */
	public function FindAccountRelations(FindAccountRelationsRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param FindProfileDocumentsRequest $request
	 *
	 * @return FindProfileDocumentsResponse
	 */
	public function FindProfileDocuments(FindProfileDocumentsRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param FindOperationsListRequest $request
	 *
	 * @return FindOperationsListResponse
	 */
	public function FindOperationsList(FindOperationsListRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param VerifyTransactionRequest $request
	 *
	 * @return VerifyTransactionResponse
	 */
	public function VerifyTransaction(VerifyTransactionRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param GetFinancialFlowsListRequest $request
	 *
	 * @return GetFinancialFlowsListResponse
	 */
	public function GetFinancialFlowsList(GetFinancialFlowsListRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param GetAccountRelationRequest $request
	 *
	 * @return GetAccountRelationResponse
	 */
	public function GetAccountRelation(GetAccountRelationRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param CreateAccountRequest $request
	 *
	 * @return long
	 */
	public function CreateAccount(CreateAccountRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param GetProfileInfoRequest $request
	 *
	 * @return GetProfileInfoResponse
	 */
	public function GetProfileInfo(GetProfileInfoRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param long $request
	 *
	 * @return FindAccountByIdResponse
	 */
	public function FindAccountById( $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param DeleteAccountRelationRequest $request
	 *
	 * @return DeleteAccountRelationResponse
	 */
	public function DeleteAccountRelation(DeleteAccountRelationRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param FindLastOperationsListRequest $request
	 *
	 * @return FindLastOperationsListResponse
	 */
	public function FindLastOperationsList(FindLastOperationsListRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param CreateProfileRequest $request
	 *
	 * @return long
	 */
	public function CreateProfile(CreateProfileRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param EditProfileRequest $request
	 *
	 * @return EditProfileResponse
	 */
	public function EditProfile(EditProfileRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param VerifyPaymentRequest $request
	 *
	 * @return VerifyPaymentResponse
	 */
	public function VerifyPayment(VerifyPaymentRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param InvoiceRequest $request
	 *
	 * @return InvoiceResponse
	 */
	public function Invoice(InvoiceRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param EditAccountRequest $request
	 *
	 * @return EditAccountResponse
	 */
	public function EditAccount(EditAccountRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param FindOperationsListByCTIDRequest $request
	 *
	 * @return FindOperationsListByCTIDResponse
	 */
	public function FindOperationsListByCTID(FindOperationsListByCTIDRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param TransferRequest $request
	 *
	 * @return TransferResponse
	 */
	public function Transfer(TransferRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param UploadProfileDocumentFileRequest $request
	 *
	 * @return UploadProfileDocumentFileResponse
	 */
	public function UploadProfileDocumentFile(UploadProfileDocumentFileRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param GetAccountPaymentPasswordChallengeRequest $request
	 *
	 * @return GetAccountPaymentPasswordChallengeResponse
	 */
	public function GetAccountPaymentPasswordChallenge(GetAccountPaymentPasswordChallengeRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param FindProfileInfoRequest $request
	 *
	 * @return FindProfileInfoResponse
	 */
	public function FindProfileInfo(FindProfileInfoRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param InvoiceBatchRequest $request
	 *
	 * @return InvoiceBatchResponse
	 */
	public function InvoiceBatch(InvoiceBatchRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param CancelTransactionRequest $request
	 *
	 * @return CancelTransactionResponse
	 */
	public function CancelTransaction(CancelTransactionRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param long $request
	 *
	 * @return FindProfileInfoByAccountIdResponse
	 */
	public function FindProfileInfoByAccountId( $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param RefundRequest $request
	 *
	 * @return RefundResponse
	 */
	public function Refund(RefundRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param EditProfileDocumentRequest $request
	 *
	 * @return EditProfileDocumentResponse
	 */
	public function EditProfileDocument(EditProfileDocumentRequest $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	/**
	 * 
	 *
	 * @param long $request
	 *
	 * @return GetOperationDetailsByIdResponse
	 */
	public function GetOperationDetailsById( $request)
	{
		$request = array($request);
		return $this->call(__FUNCTION__, $request);
	}

	// end of block


	/**
	 * Add header to array of headers to be sent along with the SOAP request.
	 *
	 * @param mixed $header Заголовок
	 *
	 * @return void
	 */
	public function addInputHeader($header)
	{
		$this->inputHeaders[] = $header;
	}

	/**
	 * If supplied, this array will be filled with the headers from the SOAP response
	 *
	 * @return array
	 */
	public function getOutputHeaders()
	{
		return $this->outputHeaders;
	}


	/**
	 * Call method of web-service
	 *
	 * @param string $method Method name
	 * @param mixed $data Data
	 * @param mixed $options Options corresponding like SoapClient->__soapCall()
	 *
	 * @return mixed
	 */
	protected function call($method, $data, $options = null)
	{
		return $this->client->__soapCall($method, $data, $options, $this->inputHeaders, $this->outputHeaders);
	}
}
?>