<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Тип, описывающий доступ к счету.
	 * Account access description type.
	 * 
 */
class AccountAccessInfo
{
	
	/**
	 * Доступ на изменение свойств счета
	 * Account attributes modification access
	 * 
	 *
	 * @var boolean
	 */
	 public $accessToWrite = null;

	/**
	 * Доступ на снятие средств со счета
	 * Account debiting access
	 * 
	 *
	 * @var boolean
	 */
	 public $accessToTakenOut = null;

	/**
	 * Доступ на зачисление средств на счет
	 * Account crediting access
	 * 
	 *
	 * @var boolean
	 */
	 public $accessToTakenIn = null;

}
?>