<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;
/**
 * Типы счетов в системе МОНЕТА.РУ.
	 * Specifies an account type in MONETA.RU.
	 * 
 */
class AccountType
{

	/**
	 * Обычный счет.
	 * Standard account.
	 * 
	 *
	 * @var int
	 */
	const AccountType1 = '1';

	/**
	 * Расширенный счет.
	 * Advanced account.
	 * 
	 *
	 * @var int
	 */
	const AccountType2 = '2';

	/**
	 * Бонус-счет.
	 * Bonus account.
	 * 
	 *
	 * @var int
	 */
	const AccountType3 = '3';

	/**
	 * Займовый счет.
	 * Loan account.
	 * 
	 *
	 * @var int
	 */
	const AccountType4 = '4';

	/**
	 * Целевой счет.
	 * Special-purpose account.
	 * 
	 *
	 * @var int
	 */
	const AccountType5 = '5';

	/**
	 * Комиссионный счет.
	 * Commission account.
	 * 
	 *
	 * @var int
	 */
	const AccountType6 = '6';

	/**
	 * Корпоративное средство платежа.
	 * Enterprise account.
	 * 
	 *
	 * @var int
	 */
	const AccountType7 = '7';

}
