<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Информация об операции.
	 * Operation details.
	 * 
 */
class AccountStatementRecord
{
	
	/**
	 * Дата операции.
	 * Operation date.
	 * 
	 *
	 * @var dateTime
	 */
	 public $date = null;

	/**
	 * Номер операции в системе МОНЕТА.РУ.
	 * MONETA.RU transaction ID.
	 * 
	 *
	 * @var long
	 */
	 public $operationId = null;

	/**
	 * Вид опрации.
	 * Operation type.
	 * 
	 *
	 * @var string
	 */
	 public $operationView = null;

	/**
	 * Наименование контрагента.
	 * Correspondent.
	 * 
	 *
	 * @var string
	 */
	 public $correspondentName = null;

	/**
	 * Номер счета контрагента в системе MONETA.RU.
	 * Correspondent account number in MONETA.RU.
	 * 
	 *
	 * @var long
	 */
	 public $correspondentAccountId = null;

	/**
	 * Номер корреспондирующего счета контрагента.
	 * Corresponding account.
	 * 
	 *
	 * @var string
	 */
	 public $correspondentAccount = null;

	/**
	 * Сумма по дебету счета.
	 * Debit amount.
	 * 
	 *
	 * @var decimal
	 */
	 public $debitAmount = null;

	/**
	 * Сумма по кредиту счета.
	 * Credit amount.
	 * 
	 *
	 * @var decimal
	 */
	 public $creditAmount = null;

	/**
	 * Назначение операции.
	 * Description.
	 * 
	 *
	 * @var string
	 */
	 public $description = null;

}
