<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Фильтр, по которому ищем выписку по счету.
	 * Filtering criteria.
	 * 
 */
class AccountStatementRequestFilter
{
	
	/**
	 * Номер счета в системе MONETA.RU.
	 * Account number in MONETA.RU.
	 * 
	 *
	 * @var long
	 */
	 public $accountId = null;

	/**
	 * Дата начала периода выборки.
	 * The start date of the period.
	 * 
	 *
	 * @var date
	 */
	 public $dateFrom = null;

	/**
	 * Дата окончания периода выборки.
	 * The end date of the period.
	 * 
	 *
	 * @var date
	 */
	 public $dateTo = null;

	/**
	 * Дополнительные атрибуты запроса. (searchInArchive = [ true | false ])
	 * Additional request parameters. (searchInArchive = [ true | false ])
	 * 
	 *
	 * @var KeyValueAttribute
	 */
	 public $attribute = null;

	/**
	 * Дополнительные атрибуты запроса. (searchInArchive = [ true | false ])
	 * Additional request parameters. (searchInArchive = [ true | false ])
	 * 
	 *
	 * @param KeyValueAttribute
	 *
	 * @return void
	 */
	public function addAttribute(KeyValueAttribute $item)
	{
		$this->attribute[] = $item;
	}

}
