<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;
/**
 * Тип платежного пароля.
	 * Payment password type.
	 * 
 */
class AccountPaymentPasswordType
{

	/**
	 * Статический платежный пароль.
	 * Static payment password.
	 * 
	 *
	 * @var string
	 */
	const STATIC = 'STATIC';

	/**
	 * SMS пароль.
	 * SMS password.
	 * 
	 *
	 * @var string
	 */
	const SMS_SIMPLE = 'SMS_SIMPLE';

}
