<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;
/**
 * Тип, описывающий статусы счетов в системе МОНЕТА.РУ. Счет может быть либо активным, либо заблокированным.
	 * Specifies a status of a MONETA.RU account.
	 * 
 */
class AccountStatus
{

	/**
	 * Активный счет.
	 * Active account.
	 * 
	 *
	 * @var int
	 */
	const AccountStatus1 = '1';

	/**
	 * Заблокированный счет.
	 * Inactive (blocked) account.
	 * 
	 *
	 * @var int
	 */
	const AccountStatus2 = '2';

	/**
	 * Закрытый счет.
	 * Closed account.
	 * 
	 *
	 * @var int
	 */
	const AccountStatus3 = '3';

}
