<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на получение выписки по лицевому счет счету.
	 * Request for getting an account statement.
	 * 
 */
class AccountStatementRequest
{
	
	/**
	 * Фильтр, по которому ищем выписку по счету.
	 * Filtering criteria.
	 * 
	 *
	 * @var AccountStatementRequestFilter
	 */
	 public $filter = null;

	/**
	 * Количество элементов, возвращаемых в результате запроса.
	 * The number of elements to return per page.
	 * 
	 *
	 * @var int
	 */
	 public $pageSize = null;

}
