<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос accountStatementRequest. Содержит выписку по счету.
	 * Response to accountStatementRequest. The response contains account statement.
	 * 
 */
class AccountStatementResponse
{
	
	/**
	 * 
	 *
	 * @var AccountStatement
	 */
	 public $accountStatement = null;

}
