<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;
/**
 * Типы счетов в системе МОНЕТА.РУ.
	 * Account types in MONETA.RU.
	 * 
 */
class AccountType
{

	/**
	 * Обычный счет
	 * Standard account
	 * 
	 *
	 * @var int
	 */
	const AccountType1 = '1';

	/**
	 * Расширенный счет
	 * Advanced account
	 * 
	 *
	 * @var int
	 */
	const AccountType2 = '2';

	/**
	 * Бонус-счет
	 * Bonus account
	 * 
	 *
	 * @var int
	 */
	const AccountType3 = '3';

	/**
	 * Займовый счет
	 * Loan account
	 * 
	 *
	 * @var int
	 */
	const AccountType4 = '4';

	/**
	 * Целевой счет
	 * Dedicated
	 * 
	 *
	 * @var int
	 */
	const AccountType5 = '5';

	/**
	 * Комиссионный счет
	 * Commission
	 * 
	 *
	 * @var int
	 */
	const AccountType6 = '6';

	/**
	 * Корпоративное средство платежа
	 * Entrprise account
	 * 
	 *
	 * @var int
	 */
	const AccountType7 = '7';

}
?>