<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос ApprovePhoneApplyCodeRequest. В ответе нет никаких данных.
	 * Если в процессе подтверждения (или отмены подтверждения) сотового телефона произошла ошибка, то возникнет Exception. Если Exception не возник - значит сотовый телефон гарантированно подтвержден (или подтверждение отменено).
	 * Response to ApprovePhoneApplyCodeRequest.
	 * If MONETA.RU confirms the phone number successfully, the response contains no data and the phone number gets the approved status. If MONETA.RU fails to confirm the phone number, the response contains an exception.
	 * 
 */
class ApprovePhoneApplyCodeResponse
{
	
}
