<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос ApprovePhoneSendConfirmationRequest.
	 * Response to ApprovePhoneSendConfirmationRequest.
	 * 
 */
class ApprovePhoneSendConfirmationResponse
{
	
	/**
	 * Номер телефона, на который было послано sms сообщение.
	 * The phone number to which MONETA.RU sends the SMS message.
	 * 
	 *
	 * @var string
	 */
	 public $phoneNumber = null;

}
