<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;
/**
 * Тип, описывающий статусы асинхронных запросов в системе МОНЕТА.РУ. Данный тип может иметь только определенные значения, описанные ниже.
	 * The status of a asynchronous task in MONETA.RU.
	 * 
 */
class AsyncStatus
{

	/**
	 * Асихронная задача в обработке.
	 * MONETA.RU is processing the asynchronous task.
	 * 
	 *
	 * @var string
	 */
	const INPROGRESS = 'INPROGRESS';

	/**
	 * Асихронная задача создана.
	 * Asynchronous task is registered in MONETA.RU.
	 * 
	 *
	 * @var string
	 */
	const CREATED = 'CREATED';

}
