<?php

// Warning! This code was generated by WSDL2PHP tool.
// author: Filippov Andrey <afi.work@gmail.com>
// see https://solo-framework-lib.googlecode.com

namespace Moneta\Types;

/**
 *
 */
class AsyncResponse
{
	/**
	 * @var GetTurnoverListResponse $GetTurnoverListResponse
	 */
	public $GetTurnoverListResponse = null;

	/**
	 * @var GetFinancialFlowsListResponse $GetFinancialFlowsListResponse
	 */
	public $GetFinancialFlowsListResponse = null;

	/**
	 * @var SimplifiedIdentificationResponse $SimplifiedIdentificationResponse
	 */
	public $SimplifiedIdentificationResponse = null;

	/**
	 * @var PingResponse $PingResponse
	 */
	public $PingResponse = null;

	/**
	 * @var PaymentResponse $PaymentResponse
	 */
	public $PaymentResponse = null;

	/**
	 * @var VerifyPaymentResponse $VerifyPaymentResponse
	 */
	public $VerifyPaymentResponse = null;

	/**
	 * @var VerifyPaymentBatchResponse $VerifyPaymentBatchResponse
	 */
	public $VerifyPaymentBatchResponse = null;

	/**
	 * @var int $asyncId
	 */
	public $asyncId = null;

	/**
	 * @var AsyncStatus $asyncStatus
	 */
	public $asyncStatus = null;

	/**
	 * @var \DateTime $expirationDate
	 */
	public $expirationDate = null;
}
