<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * 
 */
class AsyncResponse
{
	/**
	 * @var GetTurnoverListResponse $GetTurnoverListResponse
	 */
	protected $GetTurnoverListResponse = null;

	/**
	 * @var GetFinancialFlowsListResponse $GetFinancialFlowsListResponse
	 */
	protected $GetFinancialFlowsListResponse = null;

	/**
	 * @var SimplifiedIdentificationResponse $SimplifiedIdentificationResponse
	 */
	protected $SimplifiedIdentificationResponse = null;

	/**
	 * @var PingResponse $PingResponse
	 */
	protected $PingResponse = null;

	/**
	 * @var PaymentResponse $PaymentResponse
	 */
	protected $PaymentResponse = null;

	/**
	 * @var int $asyncId
	 */
	protected $asyncId = null;

	/**
	 * @var AsyncStatus $asyncStatus
	 */
	protected $asyncStatus = null;

	/**
	 * @var \DateTime $expirationDate
	 */
	protected $expirationDate = null;
}
