<?php

// Warning! This code was generated by WSDL2PHP tool.
// author: Filippov Andrey <afi.work@gmail.com>
// see https://solo-framework-lib.googlecode.com

namespace Moneta\Types;

/**
 *
 */
class AsyncRequest
{
	/**
	 * @var GetTurnoverListRequest $GetTurnoverListRequest
	 */
	public $GetTurnoverListRequest = null;

	/**
	 * @var GetFinancialFlowsListRequest $GetFinancialFlowsListRequest
	 */
	public $GetFinancialFlowsListRequest = null;

	/**
	 * @var SimplifiedIdentificationRequest $SimplifiedIdentificationRequest
	 */
	public $SimplifiedIdentificationRequest = null;

	/**
	 * @var PingRequest $PingRequest
	 */
	public $PingRequest = null;

	/**
	 * @var PaymentRequest $PaymentRequest
	 */
	public $PaymentRequest = null;

	/**
	 * @var string $callbackUrl
	 */
	public $callbackUrl = null;

	/**
	 * @var int $asyncId
	 */
	public $asyncId = null;
}
