<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на регистрацию операции с блокировкой средств на счете плательщика в пакетном режиме.
	 * Request for putting an authorization hold on the payment amount in the payer's account in batch mode.
	 * 
 */
class AuthoriseTransactionBatchRequest extends AuthoriseTransactionBatchRequestType
{
	
}
