<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Тип для запроса на регистрацию операции с блокировкой средств на счете плательщика.
	 * Transaction registration and debiting funds from payer's account request type.
	 * 
 */
class AuthoriseTransactionRequestType extends TransactionRequestType
{
	
	/**
	 * Номер операции. Необязательное поле.
	 * Transaction ID. Optional.
	 * 
	 *
	 * @var long
	 */
	 public $transactionId = null;

}
?>