<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Запрос на регистрацию операции с блокировкой средств на счете плательщика.
	 * Завершить (подтвердить) операцию можно с помощью ConfirmTransactionRequest.
	 * Если операция не будет закончена с помощью ConfirmTransactionRequest, то
	 * операция будет отменена автоматически по истечению срока блокировки.
	 * Request for transaction registration and debiting funds from payer's account.
	 * To finish (confirm) this transaction use ConfirmTransactionRequest.
	 * Authorised but not cofirmed transactions are cancelled automaticaly after authorisation expiry.
	 * 
 */
class AuthoriseTransactionRequest extends AuthoriseTransactionRequestType
{
	
}
?>