<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Запрос на регистрацию операции с блокировкой средств на счете плательщика в пакетном режиме.
	 * Request for transactions registration and debiting funds from payer's account in batch processing mode.
	 * 
 */
class AuthoriseTransactionBatchRequest extends AuthoriseTransactionBatchRequestType
{
	
}
?>