<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на регистрацию операции с блокировкой средств на счете плательщика.
	 * Завершить (подтвердить) операцию можно с помощью ConfirmTransactionRequest.
	 * Если операция не будет закончена с помощью ConfirmTransactionRequest, то операция будет отменена автоматически по истечению срока блокировки.
	 * Request for putting an authorization hold on the payment amount in the payer's account.
	 * To complete the transaction, use ConfirmTransactionRequest. If MONETA.RU does not receive ConfirmTransactionRequest until the expiration date and time, the transaction is canceled automatically.
	 * 
 */
class AuthoriseTransactionRequest extends AuthoriseTransactionRequestType
{
	
}
