<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Банковские реквизиты в системе МОНЕТА.РУ. Данные представляются в виде "ключ-значение".
	 * Возможные ключи:
	 * is_international - международные банковские реквизиты (true/false);
	 * bank - банк;
	 * bik - БИК;
	 * account - расчетный счет;
	 * corr_bank - корреспондентский банк;
	 * corr_account - корреспондентский счет;
	 * country - страна;
	 * state - регион/республика;
	 * city - город;
	 * kbk - КБК;
	 * oktmo - Общероссийский классификатор территорий муниципальных образований;
	 * kpp - КПП;
	 * Bank account details. Data is presented as key-value pairs list.
	 * Possible keys:
	 * is_international - international bank account details (true/false);
	 * bank - bank;
	 * bik - SWIFT/BIC number;
	 * account - IBAN/settlement account;
	 * corr_bank - correspondent bank;
	 * corr_account - correspondent account;
	 * country - country;
	 * state - region/state;
	 * city - city;
	 * kbk - budget classification code;
	 * oktmo - russian Classification of Objects;
	 * kpp - code reason for registration;
	 * 
 */
class BankAccount
{
	
	/**
	 * ID банковских реквизитов
	 * Bank account ID
	 * 
	 *
	 * @var long
	 */
	 public $id = null;

	/**
	 * 
	 *
	 * @var KeyValueAttribute
	 */
	 public $attribute = null;

	/**
	 * 
	 *
	 * @param KeyValueAttribute
	 *
	 * @return void
	 */
	public function addAttribute(KeyValueAttribute $item)
	{
		$this->attribute[] = $item;
	}

}
?>