<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос BlockAccountRequest. В ответе нет никаких данных.
	 * Если в процессе блокирования счета произошла ошибка, то возникнет Exception. Если Exception не возник - значит счет гарантированно заблокирован.
	 * Response to the request for blocking an account. If you blocked the account successfully, the response contains no data. If MONETA.RU cannot block the account, an error occurs.
	 * 
 */
class BlockAccountResponse extends AbstractAttributeObject
{
	
}
