<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Блокировка счета.
	 * Block an account.
	 * 
 */
class BlockAccountRequest extends AbstractAttributeObject
{
	
	/**
	 * Идентификатор счета.
	 * The identifier of the account.
	 * 
	 *
	 * @var long
	 */
	 public $id = null;

}
