<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Тип для запроса на отмену операций в пакетном режиме.
	 * Request parameters for canceling transactions in
	 * batch mode.
	 * 
 */
class CancelTransactionBatchRequestType extends EntityBatchRequestType
{
	
	/**
	 * Набор операций, которые необходимо выполнить в одном пакете. Операции выполняются в том порядке, в котором они переданы в запросе.
	 * The set of transactions that must be processed in a single batch. MONETA.RU processes transactions in the order that they are defined in the request.
	 * 
	 *
	 * @var CancelTransactionRequestType
	 */
	 public $transaction = null;

	/**
	 * Набор операций, которые необходимо выполнить в одном пакете. Операции выполняются в том порядке, в котором они переданы в запросе.
	 * The set of transactions that must be processed in a single batch. MONETA.RU processes transactions in the order that they are defined in the request.
	 * 
	 *
	 * @param CancelTransactionRequestType
	 *
	 * @return void
	 */
	public function addTransaction(CancelTransactionRequestType $item)
	{
		$this->transaction[] = $item;
	}

}
