<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Тип, описывающий атрибуты при ответе на запрос отмены операций в пакетной режиме.
	 * Response parameters for canceling transactions in batch mode.
	 * 
 */
class CancelTransactionBatchResponseType
{
	
}
