<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на отмену операций в пакетном режиме.
	 * Request for canceling transactions in batch mode.
	 * 
 */
class CancelTransactionBatchRequest extends CancelTransactionBatchRequestType
{
	
}
