<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Ответ на запрос CancelTransactionBatchRequest.
	 * Transactions cancelation response in batch processing mode.
	 * 
 */
class CancelTransactionBatchResponse
{
	
	/**
	 * Детали проведенных операций, либо описание ошибок, если операция не проведена.
	 * Порядок соответствует набору операций, переданных в CancelTransactionBatchRequest.
	 * Either transaction details or error description in order of appearance in corresponding request.
	 * 
	 *
	 * @var CancelTransactionBatchResponseType
	 */
	 public $transaction = null;

	/**
	 * Детали проведенных операций, либо описание ошибок, если операция не проведена.
	 * Порядок соответствует набору операций, переданных в CancelTransactionBatchRequest.
	 * Either transaction details or error description in order of appearance in corresponding request.
	 * 
	 *
	 * @param CancelTransactionBatchResponseType
	 *
	 * @return void
	 */
	public function addTransaction(CancelTransactionBatchResponseType $item)
	{
		$this->transaction[] = $item;
	}

}
?>