<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на отмену операции. Отменять операцию можно при выполнении всех условий:
	 * Незавершенные операции.
	 * Если есть доступ к счету плательщика и счету получателя (то есть свои внутренние операции).
	 * Request for canceling a transaction. You can cancel a transaction only if both conditions are true:
	 * The transaction is in processing (incomplete).
	 * You have access to the accounts of the payer and payee.
	 * 
 */
class CancelTransactionRequest extends CancelTransactionRequestType
{
	
}
