<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на получение состояния профиля организации (атрибуты, которые нужно заполнить) в системе MONETA.RU.
	 * Request to receive the status of the organization profile (attributes to be filled in) in MONETA.RU.
	 * 
 */
class CheckProfileRequest
{
	
	/**
	 * ID организации в системе MONETA.RU, профиль которой надо проверить.
	 * The unique identifier of the MONETA.RU organization that you want to check.
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

}
