<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос CheckProfileRequest, содержащий информацию о состоянии профиля.
	 * Response to CheckProfileRequest that contains the state of the profile.
	 * 
 */
class CheckProfileResponse
{
	
	/**
	 * Статус профиля:
	 * NONE [данные не нужны]
	 * OK [все данные указаны]
	 * DATA_REQUIRED [требуются данные]
	 * Profile status:
	 * NONE [no data required]
	 * OK [all data entered]
	 * DATA_REQUIRED [some data required]
	 * 
	 *
	 * @var string
	 */
	 public $status = null;

	/**
	 * Сумма долей учредителей (%)
	 * The status of founders' shares (%)
	 * 
	 *
	 * @var float
	 */
	 public $foundersTotalShare = null;

}
