<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на создание пользователя в системе МОНЕТА.РУ.
	 * Request for creating a MONETA.RU account.
	 * 
 */
class CheckProfileRequest
{
	
	/**
	 * ID пользователя в системе МОНЕТА.РУ, профиль которого надо проверить.
	 * The unique identifier of the MONETA.RU user that you want to check.
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

}
