<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Запрос на завершение (подтверждение) операции.
	 * Transaction confirmation request.
	 * 
 */
class ConfirmTransactionRequest extends ConfirmTransactionRequestType
{
	
}
?>