<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на завершение (подтверждение) операции.
	 * Request for confirming the transaction.
	 * 
 */
class ConfirmTransactionRequest extends ConfirmTransactionRequestType
{
	
}
