<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос завершения операции.
	 * Response to a transaction confirmation request.
	 * 
 */
class ConfirmTransactionResponse extends OperationInfo
{
	
}
