<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Договор в системе МОНЕТА.РУ. Данные представляются в виде "ключ-значение".
	 * Возможные ключи договора:
	 * num - номер договора;
	 * unitid - ID юнита, у которого создан договор;
	 * own - true-создан для указанного в запросе юнита, false-создан для родительского юнита;
	 * unitname - если own=false, то данное поле содержит имя юнита;
	 * datestart - дата начала договора;
	 * datestop - дата окончания договора;
	 * status - статус договора:
	 * CREATED - сформирован,
	 * SIGNED - подписан,
	 * ACTIVE - активный,
	 * PAUSED - приостановлен,
	 * INACTIVE - расторгнут;
	 * type - тип договора:
	 * PARTNER - договор,
	 * VIRTUAL - виртуальный договор;
	 * Contract information. Data is presented as key-value pairs list.
	 * Possible contract keys:
	 * num - contract number;
	 * unitid - Structure ID of agreement;
	 * own - true-own agreement, false-inherited agreement;
	 * unitname - ancestor structure name if own=false;
	 * datestart - contract date start;
	 * datestop - contract date end;
	 * status - contract status:
	 * CREATED,
	 * SIGNED,
	 * ACTIVE,
	 * PAUSED,
	 * INACTIVE;
	 * type - contract type:
	 * PARTNER - contract,
	 * VIRTUAL - virtual contract;
	 * 
 */
class Contract
{
	
	/**
	 * ID договора
	 * Contract ID
	 * 
	 *
	 * @var long
	 */
	 public $id = null;

	/**
	 * 
	 *
	 * @var KeyValueAttribute
	 */
	 public $attribute = null;

	/**
	 * 
	 *
	 * @param KeyValueAttribute
	 *
	 * @return void
	 */
	public function addAttribute(KeyValueAttribute $item)
	{
		$this->attribute[] = $item;
	}

}
?>