<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Запрос на создание пользователя в системе МОНЕТА.РУ.
	 * New user registration request.
	 * 
 */
class CreateProfileRequest
{
	
	/**
	 * ID родительского пользователя в системе МОНЕТА.РУ, к которому будет принадлежать
	 * создаваемый пользователь. Необязательное поле. Если поле не задано,
	 * то пользователь будет принадлежать тому пользователю, от имени
	 * которого работает web service.
	 * Structure ID in MONETA.RU.
	 * If ommited then authenticated user's structure ID is used.
	 * Optional.
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

	/**
	 * Тип пользователя - "client" или "organization"
	 * Profile type. See also ProfileType description.
	 * 
	 *
	 * @var string
	 */
	 public $profileType = null;

	/**
	 * Данные создаваемого пользователя. Данные представлены в виде "ключ-значение".
	 * Ключи данных зависят от типа пользователя (ProfileType)
	 * User profile information in key-value pairs list.
	 * Supported keys depend on ProfileType.
	 * 
	 *
	 * @var Profile
	 */
	 public $profile = null;

}
?>