<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос создания документа в профиле.
	 * Response to CreateProfileDocumentRequest.
	 * 
 */
class CreateProfileDocumentResponse
{
	
	/**
	 * Идентификатор документа в системе MONETA.RU.
	 * Unique identifier of the document in MONETA.RU.
	 * 
	 *
	 * @var long
	 */
	 public $id = null;

}
