<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос создания банковских реквизитов.
	 * Response to the request for creating a bank account.
	 * 
 */
class CreateBankAccountResponse
{
	
	/**
	 * Идентификатор банковских реквизитов в системе MONETA.RU.
	 * Unique identifier of the bank account in MONETA.RU.
	 * 
	 *
	 * @var long
	 */
	 public $id = null;

}
