<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Ответ на запрос создания документа в профиле.
	 * Profile's document registration response.
	 * 
 */
class CreateProfileDocumentResponse
{
	
	/**
	 * Идентификатор документа в системе МОНЕТА.РУ
	 * Document identificator in MONETA.RU
	 * 
	 *
	 * @var long
	 */
	 public $id = null;

}
?>