<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;
/**
 * Тип, описывающий валюты, используемые в системе MONETA.RU. Данный тип может иметь только строго определенные значения, описанные ниже.
	 * Specifies the currency that is used in a transaction.
	 * 
 */
class Currency
{

	/**
	 * 
	 *
	 * @var string
	 */
	const RUB = 'RUB';

	/**
	 * 
	 *
	 * @var string
	 */
	const USD = 'USD';

	/**
	 * 
	 *
	 * @var string
	 */
	const EUR = 'EUR';

	/**
	 * 
	 *
	 * @var string
	 */
	const GBP = 'GBP';

}
