<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;
/**
 * Тип, описывающий валюты, используемые в системе МОНЕТА.РУ.
	 * Данный тип может иметь только строго определенные значения, описанные ниже.
	 * Currency type in MONETA.RU.
	 * Must be one of values listed below.
	 * 
 */
class Currency
{

	/**
	 * 
	 *
	 * @var string
	 */
	const RUB = 'RUB';

	/**
	 * 
	 *
	 * @var string
	 */
	const USD = 'USD';

	/**
	 * 
	 *
	 * @var string
	 */
	const EUR = 'EUR';

	/**
	 * 
	 *
	 * @var string
	 */
	const GBP = 'GBP';

}
?>