<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на удаление шаблона операции.
	 * 
 */
class DeleteOperationTemplateRequest
{
	
	/**
	 * Идентификатор шаблона операции.
	 * 
	 *
	 * @var long
	 */
	 public $id = null;

}
