<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос DeleteAccountRelationRequest.
	 * В ответе нет никаких данных.
	 * Если в процессе сохранения счета произошла ошибка, то возникнет Exception.
	 * Если Exception не возник - значит делегированный доступ гарантированно удален.
	 * Delete account relation response.
	 * Response contains no data unless some error has occured while modification.
	 * If reponse has no Exception then delegated access is deleted successfully.
	 * 
 */
class DeleteAccountRelationResponse
{
	
}
?>