<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос DeleteOperationTemplateRequest.
	 * В ответе нет никаких данных. Если в процессе удаления шаблона произошла ошибка, то возникнет Exception. Если Exception не возник - значит шаблон операции гарантированно удален.
	 * Response to DeleteOperationTemplateRequest.
	 * The response contains no data. If MONETA.RU cannot delete operation template, an error occurs.
	 * 
 */
class DeleteOperationTemplateResponse
{
	
}
