<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;
/**
 * Типы документов, поддерживаемые в системе МОНЕТА.РУ.
	 * Document type supported in MONETA.RU.
	 * 
 */
class DocumentType
{

	/**
	 * Паспорт
	 * Civil passport
	 * 
	 *
	 * @var string
	 */
	const PASSPORT = 'PASSPORT';

	/**
	 * Водительское удостоверение
	 * User's driving licence
	 * 
	 *
	 * @var string
	 */
	const DRIVING_LICENCE = 'DRIVING_LICENCE';

	/**
	 * Военный билет
	 * Military ID
	 * 
	 *
	 * @var string
	 */
	const MILITARY_ID = 'MILITARY_ID';

	/**
	 * Другой документ
	 * Other document
	 * 
	 *
	 * @var string
	 */
	const OTHER = 'OTHER';

	/**
	 * 
	 *
	 * @var string
	 */
	const CUSTOM = 'CUSTOM';

}
?>