<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;
/**
 * Типы документов, поддерживаемые в системе МОНЕТА.РУ.
	 * Document types that are supported in MONETA.RU.
	 * 
 */
class DocumentType
{

	/**
	 * Паспорт.
	 * Civil passport.
	 * 
	 *
	 * @var string
	 */
	const PASSPORT = 'PASSPORT';

	/**
	 * Водительское удостоверение.
	 * Driver's licence.
	 * 
	 *
	 * @var string
	 */
	const DRIVING_LICENCE = 'DRIVING_LICENCE';

	/**
	 * Военный билет.
	 * Military ID.
	 * 
	 *
	 * @var string
	 */
	const MILITARY_ID = 'MILITARY_ID';

	/**
	 * Другой документ.
	 * Other document.
	 * 
	 *
	 * @var string
	 */
	const OTHER = 'OTHER';

	/**
	 * Лицензия для деятельности партнера.
	 * Licence for partner activity.
	 * 
	 *
	 * @var string
	 */
	const PARTNER_LICENCE = 'PARTNER_LICENCE';

	/**
	 * Документ PASSPORT для нерезидентов.
	 * PASSPORT for non resident partner.
	 * 
	 *
	 * @var string
	 */
	const IDENTITY_DOCUMENT = 'IDENTITY_DOCUMENT';

	/**
	 * Административные документ, доступный только для админу.
	 * Document available only for administrator.
	 * 
	 *
	 * @var string
	 */
	const ADMINISTRATIVE = 'ADMINISTRATIVE';

	/**
	 * 
	 *
	 * @var string
	 */
	const CUSTOM = 'CUSTOM';

}
