<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на редактирование банковских реквизитов пользователя.
	 * Request for editing a bank account.
	 * 
 */
class EditBankAccountRequest extends BankAccount
{
	
	/**
	 * Пользователь, которому принадлежат банковские реквизиты.
	 * Если это поле не задано, то банковские реквизиты ищются для текущего пользователя.
	 * The unique identifier of the user who owns the bank account.
	 * If you omit this element, MONETA.RU uses the ID of the user who sends the request.
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

	/**
	 * 
	 * 
	 *
	 * @var long
	 */
	 public $profileId = null;

}
