<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос EditProfileRequest.
	 * В ответе нет никаких данных.
	 * Если в процессе сохранения пользователя произошла ошибка, то возникнет Exception.
	 * Если Exception не возник - значит пользователь гарантированно сохранен.
	 * Profile modification response.
	 * Response contains no data unless error has occured while saving information
	 * and Exception returned as a result.
	 * 
 */
class EditProfileResponse
{
	
}
?>