<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Запрос на редактирование документа пользователя.
	 * Profile's document modification request.
	 * 
 */
class EditProfileDocumentRequest extends Document
{
	
	/**
	 * Пользователь, которому принадлежит данный документ.
	 * Если это поле не задано, то документ ищется для текущего пользователя.
	 * Необязательное поле.
	 * Structure element, where the document belongs to.
	 * If omitted authenticated user's structure is used.
	 * Optional.
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

}
?>