<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос EditAccountRequest.
	 * В ответе нет никаких данных.
	 * Если в процессе сохранения счета произошла ошибка, то возникнет Exception.
	 * Если Exception не возник - значит счет гарантированно сохранен.
	 * Account modification response.
	 * Response contains no data unless some error has occured while modification.
	 * If reponse has no Exception then account is modified successfully.
	 * 
 */
class EditAccountResponse
{
	
}
?>