<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Запрос на редактирование данных пользователя в системе МОНЕТА.РУ.
	 * Profile information modification request.
	 * 
 */
class EditProfileRequest
{
	
	/**
	 * ID пользователя в системе МОНЕТА.РУ, данные которого надо отредактировать.
	 * Structure ID of profile for modification.
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

	/**
	 * Данные редактируемого пользователя. Данные представлены в виде "ключ-значение".
	 * Ключи данных зависят от типа редактируемого пользователя (client или organization)
	 * User profile information in key-value pairs list.
	 * Supported keys depend on ProfileType.
	 * 
	 *
	 * @var Profile
	 */
	 public $profile = null;

}
?>