<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос EditProfileDocumentRequest.
	 * В ответе нет никаких данных. Если в процессе сохранения документа произошла ошибка, то возникнет Exception.
	 * Если Exception не возник - значит документ гарантированно сохранен.
	 * Response to EditProfileDocumentRequest.
	 * If MONETA.RU saves the document changes successfully, the response contains no data.
	 * If MONETA.RU fails to save changes to the document, an error occurs.
	 * 
 */
class EditProfileDocumentResponse
{
	
}
