<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Запрос на редактирование данных пользователя в системе МОНЕТА.РУ.
	 * Profile information modification request.
	 * 
 */
class EditProfileRequest
{
	
	/**
	 * ID пользователя в системе МОНЕТА.РУ, данные которого надо отредактировать.
	 * Structure ID of profile for modification.
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

	/**
	 * Данные редактируемого пользователя. Данные представлены в виде "ключ-значение".
	 * Ключи данных зависят от типа редактируемого пользователя (client или organization)
	 * User profile information in key-value pairs list.
	 * Supported keys depend on ProfileType.
	 * 
	 *
	 * @var Profile
	 */
	 public $profile = null;

	/**
	 * ID структуры, куда необходимо перенести данного пользователя.
	 * К указанной структуре должен быть доступ, а также действующий договор должен разрешать создание пользователя с нужным типом (client или organization)
	 * Structure ID of new parent for current profile.
	 * An access to specified StructureID has to be granted, and destination's contract has to allow descending profiles.
	 * 
	 *
	 * @var long
	 */
	 public $parentId = null;

}
?>