<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос EditProfileRequest.
	 * В ответе нет никаких данных. Если в процессе сохранения пользователя произошла ошибка, то возникнет Exception. Если Exception не возник - значит пользователь гарантированно сохранен.
	 * Response to EditProfileRequest.
	 * The response contains no data, if MONETA.RU applies your changes to the user profile. If MONETA.RU cannot apply your changes to the user profile, an error occurs.
	 * 
 */
class EditProfileResponse
{
	
}
