<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос EditBankAccountRequest.
	 * В ответе нет никаких данных. Если в процессе сохранения банковских реквизитов произошла ошибка, то возникнет Exception.
	 * Если Exception не возник - значит банковские реквизиты гарантированно сохранены.
	 * Response to EditBankAccountRequest.
	 * The response contains no data, if MONETA.RU edited the bank account successfully.
	 * 
 */
class EditBankAccountResponse
{
	
}
