<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на редактирование данных пользователя в системе MONETA.RU.
	 * Request for editing a MONETA.RU user profile.
	 * 
 */
class EditProfileRequest
{
	
	/**
	 * ID пользователя в системе MONETA.RU, данные которого надо отредактировать.
	 * The unique identifier of the MONETA.RU user that you want to edit.
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

	/**
	 * 
	 * 
	 *
	 * @var long
	 */
	 public $profileId = null;

	/**
	 * Данные редактируемого пользователя. Данные представлены в виде "ключ-значение".
	 * Ключи данных зависят от типа редактируемого пользователя (client или organization).
	 * User profile information in the list of key-value pairs.
	 * The list of supported keys depends on ProfileType.
	 * 
	 *
	 * @var Profile
	 */
	 public $profile = null;

	/**
	 * ID структуры, куда необходимо перенести данного пользователя.
	 * К указанной структуре должен быть доступ, а также действующий договор должен разрешать создание пользователя с нужным типом (client или organization).
	 * The unique identifier of the parent MONETA.RU profile that must own the profile that you edit.
	 * The user who sends this request must have access to the specified profile. And your agreement must allow creating profiles of this type.
	 * 
	 *
	 * @var long
	 */
	 public $parentId = null;

}
