<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос EditAccountRequest.
	 * В ответе нет никаких данных.
	 * Если в процессе сохранения счета произошла ошибка, то возникнет Exception.
	 * Если Exception не возник - значит счет гарантированно сохранен.
	 * Response to the request for editing an account. If you changed the account settings successfully, the response contains no data. If MONETA.RU cannot change the account settings, an error occurs.
	 * 
 */
class EditAccountResponse
{
	
}
