<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Базовый тип, содержащий атрибут version.
	 * A base type that contains the version attribute.
	 * 
 */
class Entity
{
	
	/**
	 * 
	 *
	 * @var string
	 */
	 public $version = null;

}
