<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Базовый тип, содержащий атрибут "version".
	 * Base type containing "version" attribute.
	 * 
 */
class Entity
{
	
	/**
	 * 
	 *
	 * @var string
	 */
	 public $version = null;

}
?>