<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Ответ на запрос FindBankAccountsRequest.
	 * Bank account details by structure ID searching response.
	 * 
 */
class FindBankAccountsResponse
{
	
	/**
	 * 
	 *
	 * @var BankAccount
	 */
	 public $bankAccount = null;

	/**
	 * 
	 *
	 * @param BankAccount
	 *
	 * @return void
	 */
	public function addBankAccount(BankAccount $item)
	{
		$this->bankAccount[] = $item;
	}

}
?>