<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Ответ, который содержит список счетов.
	 * Accounts searching response containing the list of accounts.
	 * 
 */
class FindAccountsListResponse
{
	
	/**
	 * 
	 *
	 * @var AccountInfo
	 */
	 public $account = null;

	/**
	 * 
	 *
	 * @param AccountInfo
	 *
	 * @return void
	 */
	public function addAccount(AccountInfo $item)
	{
		$this->account[] = $item;
	}

}
?>