<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Поиск пользователя в системе МОНЕТА.РУ по заданному фильтру.
	 * В результате возвратится список пользователей, разбитый на страницы
	 * Profile searching by filter parameters.
	 * Result contains paged profile list.
	 * 
 */
class FindProfileInfoRequest extends Entity
{
	
	/**
	 * Настройки страницы данных. Необязательное поле.
	 * Paging settings. Optional.
	 * 
	 *
	 * @var Pager
	 */
	 public $pager = null;

	/**
	 * Фильтр, по которому ищем данные
	 * Searching filter
	 * 
	 *
	 * @var FindProfileInfoRequestFilter
	 */
	 public $filter = null;

}
?>