<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Запрос на получение документов пользователя.
	 * Profile's documents retrieval request.
	 * 
 */
class FindProfileDocumentsRequest
{
	
	/**
	 * ID пользователя, документы которого запрашиваются.
	 * Structure ID containing documents.
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

}
?>