<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос FindLastOperationsListRequest. В результате возвращается список последних операций.
	 * Response to FindLastOperationsListRequest that contains the list of last transactions.
	 * 
 */
class FindLastOperationsListResponse extends OperationInfoList
{
	
}
