<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос FindOperationsListByCTIDRequest.
	 * В результате возвращается список операций, разбитый по страницам.
	 * Response to the request for searching transactions by a merchant transaction ID.
	 * The response might include multiple transactions. If the list of transactions is long, the response is split into pages.
	 * 
 */
class FindOperationsListByCTIDResponse extends OperationInfoList
{
	
}
