<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Запрос на получение списка операций по заданному фильтру.
	 * Обязательными в фильтре являются только поля с датами периода.
	 * Все остальные поля в фильтре необязательные.
	 * Если данные не найдены, то size в ответе равен 0.
	 * Transaction searching by given filter.
	 * Filter requires date period values to be set.
	 * Other parameters are optional.
	 * Response element "size" is 0 if no data found.
	 * 
 */
class FindOperationsListRequest
{
	
	/**
	 * Настройки страницы данных. Необязательное поле.
	 * Paging settings. Optional.
	 * 
	 *
	 * @var Pager
	 */
	 public $pager = null;

	/**
	 * Фильтр, по которому ищем операции.
	 * Transactions filter.
	 * 
	 *
	 * @var FindOperationsListRequestFilter
	 */
	 public $filter = null;

}
?>