<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос FindAccountByAliasRequest.
	 * В ответе содержится информация по счету.
	 * Account searching by account alias response.
	 * Response contains Account information.
	 * 
 */
class FindAccountByAliasResponse
{
	
	/**
	 * 
	 *
	 * @var AccountInfo
	 */
	 public $account = null;

}
?>