<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Запрос на получение данных договора по ID пользователя. Если данные не найдены, возвращается пустой список.
	 * Request for contract information by structure ID. Empty list if no data found.
	 * 
 */
class FindContractsRequest extends Entity
{
	
	/**
	 * ID пользователя в системе МОНЕТА.РУ. Если это поле не задано, то используется текущий пользователь. Необязательное поле.
	 * Structure ID. If omitted authenticated user's structure is used. Optional.
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

}
?>