<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Ответ на запрос FindProfileDocumentsRequest.
	 * Profile's documents retrieval response.
	 * 
 */
class FindProfileDocumentsResponse
{
	
	/**
	 * Список найденных документов. Если документов нет - список пустой.
	 * Found documents list. Empty if no documents are found.
	 * 
	 *
	 * @var Document
	 */
	 public $document = null;

	/**
	 * Список найденных документов. Если документов нет - список пустой.
	 * Found documents list. Empty if no documents are found.
	 * 
	 *
	 * @param Document
	 *
	 * @return void
	 */
	public function addDocument(Document $item)
	{
		$this->document[] = $item;
	}

}
?>