<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Ответ на запрос FindAccountRelationsRequest.
	 * Response containing the list of delegated users.
	 * 
 */
class FindAccountRelationsResponse
{
	
	/**
	 * Список найденных пользователей, которые имеют делегированный доступ к указанному счету. Если пользователей нет - список пустой.
	 * List of found users having delegated account access. The list is empty if no users are found.
	 * 
	 *
	 * @var AccountRelation
	 */
	 public $accountRelation = null;

	/**
	 * Список найденных пользователей, которые имеют делегированный доступ к указанному счету. Если пользователей нет - список пустой.
	 * List of found users having delegated account access. The list is empty if no users are found.
	 * 
	 *
	 * @param AccountRelation
	 *
	 * @return void
	 */
	public function addAccountRelation(AccountRelation $item)
	{
		$this->accountRelation[] = $item;
	}

}
?>