<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос FindOperationsListRequest.
	 * В результате возвращается список операций, разбитый по страницам.
	 * Response to FindOperationsListRequest.
	 * The response might include multiple transactions. A long list of transactions might be split into multiple pages
	 * 
 */
class FindOperationsListResponse extends OperationInfoList
{
	
}
