<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос FindProfileInfoRequest.
	 * Данные в ответе разбиты по страницам.
	 * Если данные не найдены, то size в ответе равен 0.
	 * Profile searching response.
	 * Result is paged.
	 * Response element "size" is 0 if no data found.
	 * 
 */
class FindProfileInfoResponse
{
	
	/**
	 * Количество пользователей, возвращаемых в результате запроса.
	 * Profiles per page.
	 * 
	 *
	 * @var long
	 */
	 public $pageSize = null;

	/**
	 * Номер текущей страницы. Нумерация начинается с 1
	 * Current page number starting from 1.
	 * 
	 *
	 * @var long
	 */
	 public $pageNumber = null;

	/**
	 * Сколько всего страниц с пользователями возможно по данному
	 * запросу
	 * Total count of pages.
	 * 
	 *
	 * @var long
	 */
	 public $pagesCount = null;

	/**
	 * Размер текущей страницы. Он всегда <= pageSize. На последней
	 * странице может быть < pageSize
	 * Profiles count in current page.
	 * 
	 *
	 * @var long
	 */
	 public $size = null;

	/**
	 * Общее количество пользователей, которое можно получить в данной
	 * выборке
	 * Total profiles count matched by searching filter.
	 * 
	 *
	 * @var long
	 */
	 public $totalSize = null;

	/**
	 * Список пользователей
	 * Profile list
	 * 
	 *
	 * @var Profile
	 */
	 public $profile = null;

	/**
	 * Список пользователей
	 * Profile list
	 * 
	 *
	 * @param Profile
	 *
	 * @return void
	 */
	public function addProfile(Profile $item)
	{
		$this->profile[] = $item;
	}

}
?>