<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос FindAccountByIdRequest. В ответе содержится информация по счету.
	 * Response to FindAccountByIdRequest. The response contains information about the account that has the specified account number.
	 * 
 */
class FindAccountByIdResponse
{
	
	/**
	 * 
	 *
	 * @var AccountInfo
	 */
	 public $account = null;

}
