<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос FindAccountByAliasRequest. В ответе содержится информация по счету.
	 * Response to FindAccountByAliasRequest. The response contains information about the account that has the specified alias.
	 * 
 */
class FindAccountByAliasResponse
{
	
	/**
	 * 
	 *
	 * @var AccountInfo
	 */
	 public $account = null;

}
