<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос FindProfileInfoByAccountIdRequest.
	 * Response to FindProfileInfoByAccountIdRequest.
	 * 
 */
class FindProfileInfoByAccountIdResponse
{
	
	/**
	 * Номер счета пользователя в системе МОНЕТА.РУ.
	 * MONETA.RU account number.
	 * 
	 *
	 * @var long
	 */
	 public $accountId = null;

	/**
	 * Валюта счета.
	 * Account currency.
	 * 
	 *
	 * @var string
	 */
	 public $currency = null;

	/**
	 * Данные пользователя в системе МОНЕТА.РУ.
	 * Information about a MONETA.RU user profile.
	 * 
	 *
	 * @var Profile
	 */
	 public $profile = null;

}
