<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на получение бинарных данных, ассоциированных с указанным документом.
	 * Request for binary data that is associated with the specified document.
	 * 
 */
class FindProfileDocumentFilesRequest
{
	
	/**
	 * 
	 *
	 * @var long
	 */
	 public $documentId = null;

}
