<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Ответ, содержащий бинарные данные, ассоциированные с указанным в запросе документом.
	 * Response containing binary data associated with document given in request.
	 * 
 */
class FindProfileDocumentFilesResponse
{
	
	/**
	 * 
	 *
	 * @var File
	 */
	 public $file = null;

	/**
	 * 
	 *
	 * @param File
	 *
	 * @return void
	 */
	public function addFile(File $item)
	{
		$this->file[] = $item;
	}

}
?>