<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Ответ на запрос FindOperationsListRequest.
	 * В результате возвращается список операций, разбитый по страницам.
	 * Transaction searching response.
	 * Result contains paged transactions list.
	 * 
 */
class FindOperationsListResponse extends OperationInfoList
{
	
}
?>