<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Запрос на получение списка пользователей, которые имеют делегированный доступ к указанному счету.
	 * Request to find delegated users for specified account ID.
	 * 
 */
class FindAccountRelationsRequest
{
	
	/**
	 * Номер счета в системе МОНЕТА.РУ.
	 * Account number.
	 * 
	 *
	 * @var long
	 */
	 public $accountId = null;

}
?>