<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос FindProfileDocumentsRequest.
	 * Response to FindProfileDocumentsRequest.
	 * 
 */
class FindProfileDocumentsResponse
{
	
	/**
	 * Список найденных документов. Если документов нет - список пустой.
	 * The list of documents. IF MONETA.RU found no documents that belong to the specified user, the response contains an empty list.
	 * 
	 *
	 * @var Document
	 */
	 public $document = null;

	/**
	 * Список найденных документов. Если документов нет - список пустой.
	 * The list of documents. IF MONETA.RU found no documents that belong to the specified user, the response contains an empty list.
	 * 
	 *
	 * @param Document
	 *
	 * @return void
	 */
	public function addDocument(Document $item)
	{
		$this->document[] = $item;
	}

}
