<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос FindOperationTemplatesRequest.
	 * Response to FindOperationTemplatesRequest.
	 * 
 */
class FindOperationTemplatesResponse
{
	
	/**
	 * Список шаблонов.
	 * 
	 *
	 * @var AbstractAttributeObject
	 */
	 public $operationTemplate = null;

	/**
	 * Список шаблонов.
	 * 
	 *
	 * @param AbstractAttributeObject
	 *
	 * @return void
	 */
	public function addOperationTemplate(AbstractAttributeObject $item)
	{
		$this->operationTemplate[] = $item;
	}

}
