<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос предварительного расчета сумм и комиссий.
	 * Может использоваться для информирования пользователя о приблизительной сумме и комиссии операции.
	 * Фактические значения могут отличаться, если к моменту проведения операции
	 * доступны новые правила тарификации или новые курсы обмена валют.
	 * Response to a request for estimating transaction amounts and fees.
	 * Use information from this response to inform customers about the estimated amount and fee of transaction.
	 * Actual values may differ if newer financial rules and currency exchange rates
	 * are applied when processing a transaction.
	 * 
 */
class ForecastTransactionResponse extends ForecastTransactionResponseType
{
	
}
