<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Запрос предварительного расчета сумм и комиссий по параметрам операции.
	 * Request for amount and fee preliminary calculation by transaction parameters.
	 * 
 */
class ForecastTransactionRequest extends TransactionRequestType
{
	
}
?>