<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Получить запрос для платежного пароля.
	 * Request for a challenge passcode. Use this request if a user gets payment passwords by SMS or uses a list of indexed transaction authentication numbers (TANs).
	 * 
 */
class GetAccountPaymentPasswordChallengeRequest
{
	
	/**
	 * Номер счета.
	 * Account number.
	 * 
	 *
	 * @var long
	 */
	 public $accountId = null;

}
