<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Ответ на запрос GetAccountRelationRequest.
	 * Response containing detailed information for delegated access.
	 * 
 */
class GetAccountRelationResponse
{
	
	/**
	 * 
	 *
	 * @var AccountRelation
	 */
	 public $accountRelation = null;

}
?>