<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Получить запрос для платежного пароля
	 * Receive challenge for payment password
	 * 
 */
class GetAccountPaymentPasswordChallengeRequest
{
	
	/**
	 * Номер счета
	 * Account number
	 * 
	 *
	 * @var long
	 */
	 public $accountId = null;

}
?>