<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Ответ содержит строку запроса для платежного пароля
	 * Response contains of challenge string for payment password
	 * 
 */
class GetAccountPaymentPasswordChallengeResponse
{
	
	/**
	 * Запрос для платежного пароля
	 * Challenge of payment password
	 * 
	 *
	 * @var string
	 */
	 public $paymentPasswordChallenge = null;

}
?>