<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на получение данных по делегированному доступу.
	 * Request for delegated access details.
	 * 
 */
class GetAccountRelationRequest
{
	
	/**
	 * Номер счета в системе MONETA.RU.
	 * MONETA.RU account number.
	 * 
	 *
	 * @var long
	 */
	 public $accountId = null;

	/**
	 * Email пользователя.
	 * Email address of the user.
	 * 
	 *
	 * @var string
	 */
	 public $principalEmail = null;

}
