<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * 
 */
class GetFinancialFlowsListResponseFinancialFlow
{
	
	/**
	 * Дата финансового потока (формат yyyy-mm)
	 * Financial flow date (in yyyy-mm format)
	 * 
	 *
	 * @var string
	 */
	 public $date = null;

	/**
	 * Есть ли доступ к финансовому потоку плательщика
	 * Does user have access to payer financial flow
	 * 
	 *
	 * @var boolean
	 */
	 public $payerSideAccess = null;

	/**
	 * ID финансового потока плательщика
	 * Payer's financial flow ID
	 * 
	 *
	 * @var long
	 */
	 public $payerFlowId = null;

	/**
	 * Название финансового потока плательщика
	 * Payer's financial flow name
	 * 
	 *
	 * @var string
	 */
	 public $payerFlowName = null;

	/**
	 * Валюта финансового потока плательщика
	 * Payer's financial flow currency
	 * 
	 *
	 * @var string
	 */
	 public $payerCurrencyCode = null;

	/**
	 * Есть ли доступ к финансовому потоку получателя
	 * Does user have access to payee financial flow
	 * 
	 *
	 * @var boolean
	 */
	 public $payeeSideAccess = null;

	/**
	 * ID финансового потока получателя
	 * Payee's financial flow ID
	 * 
	 *
	 * @var long
	 */
	 public $payeeFlowId = null;

	/**
	 * Название финансового потока получателя
	 * Payee's financial flow name
	 * 
	 *
	 * @var string
	 */
	 public $payeeFlowName = null;

	/**
	 * Валюта финансового потока получателя
	 * Payee's financial flow currency
	 * 
	 *
	 * @var string
	 */
	 public $payeeCurrencyCode = null;

	/**
	 * Сумма, списанная с плательщика
	 * Amount debited from payer
	 * 
	 *
	 * @var decimal
	 */
	 public $payerDebited = null;

	/**
	 * Сумма, удержанная с плательщика
	 * Withholding fee from debited amount
	 * 
	 *
	 * @var decimal
	 */
	 public $payerWithheld = null;

	/**
	 * Сумма комиссии плательщика
	 * Payer's fee
	 * 
	 *
	 * @var decimal
	 */
	 public $payerFee = null;

	/**
	 * Сумма обменной комиссии плательщика
	 * Payer's exchange fee
	 * 
	 *
	 * @var decimal
	 */
	 public $payerExchangeFee = null;

	/**
	 * Сумма, зачисленная получателю
	 * Amount credited to payee
	 * 
	 *
	 * @var decimal
	 */
	 public $payeeCredited = null;

	/**
	 * Сумма комисии получателя
	 * Payee's fee
	 * 
	 *
	 * @var decimal
	 */
	 public $payeeFee = null;

	/**
	 * Количество операций в данном финансовом потоке
	 * Transactions quantity
	 * 
	 *
	 * @var long
	 */
	 public $transactionsCount = null;

	/**
	 * Категория операций в данном финансовом потоке (возвращается, если в запросе categoryDetails=true)
	 * Financial flow transactions category (if categoryDetails=true in request)
	 * 
	 *
	 * @var string
	 */
	 public $operationTypeCategory = null;

	/**
	 * Состояние операций в данном финансовом потоке
	 * Financial flow transactions state
	 * 
	 *
	 * @var string
	 */
	 public $operationStatusState = null;

}
?>