<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос получения информации по операции.
	 * Response to the transaction details request.
	 * 
 */
class GetOperationDetailsByIdResponse
{
	
	/**
	 * 
	 *
	 * @var OperationInfo
	 */
	 public $operation = null;

}
