<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Запрос на получение данных пользователя по ID пользователя.
	 * Если данные не найдены, возникает Exception.
	 * Request for profile information by structure ID.
	 * Exception is thrown if no data found.
	 * 
 */
class GetProfileInfoRequest extends Entity
{
	
	/**
	 * ID пользователя в системе МОНЕТА.РУ.
	 * Если это поле не задано, то используется текущий пользователь.
	 * Необязательное поле.
	 * Structure ID.
	 * If omitted authenticated user's structure is used.
	 * Optional.
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

}
?>