<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос GetPersonificationCodeRequest.
	 * Response to GetPersonificationCodeRequest.
	 * 
 */
class GetPersonificationCodeResponse
{
	
	/**
	 * Код, с помощью которого можно произвести идентификацию пользователя.
	 * User identification code.
	 * 
	 *
	 * @var string
	 */
	 public $personificationCode = null;

}
