<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на получение кода, с помощью которого можно произвести идентификацию пользователя.
	 * Request for a user identification code.
	 * 
 */
class GetPersonificationCodeRequest
{
	
}
