<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Получение информации об итогах по месяцам.
	 * Если данные не найдены, то size в ответе равен 0.
	 * Turnovers information request.
	 * Response element "size" is 0 if no data found.
	 * 
 */
class GetTurnoverListRequest
{
	
	/**
	 * ID пользователя в системе МОНЕТА.РУ. Если это поле не задано, то используется текущий пользователь. Необязательное поле.
	 * Structure identificator in MONETA.RU. If omitted authenticated user's structure is used. Optional.
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

	/**
	 * Дата начала периода. Дата берется с начала указанного месяца.
	 * Period starting date. Only year and month is taken.
	 * 
	 *
	 * @var date
	 */
	 public $dateFrom = null;

	/**
	 * Дата окончания периода.
	 * В дате устанавливается конец указанного месяца.
	 * Если дата не установлена, то берется конец месяца из даты dateFrom.
	 * Period ending date.
	 * The end of given month is taken.
	 * If omitted the month of "dateFrom" is taken.
	 * 
	 *
	 * @var date
	 */
	 public $dateTo = null;

	/**
	 * Список счетов, которые учитываются в итогах по месяцам
	 * Accounts numbers for turnovers
	 * 
	 *
	 * @var long
	 */
	 public $accountIds = null;

	/**
	 * Список счетов, которые учитываются в итогах по месяцам
	 * Accounts numbers for turnovers
	 * 
	 *
	 * @param long
	 *
	 * @return void
	 */
	public function addAccountIds(long $item)
	{
		$this->accountIds[] = $item;
	}

	/**
	 * Валюта, которая учитывается в итогах по месяцам
	 * Currency of accounts for turnovers
	 * 
	 *
	 * @var string
	 */
	 public $currencyCode = null;

	/**
	 * Если groupByCurrency=true, то в ответе делается группировка по валюте
	 * If flag is switched on, turnovers will be grouped by currency
	 * 
	 *
	 * @var boolean
	 */
	 public $groupByCurrency = null;

	/**
	 * Категория операций, которая учитывается в итогах по месяцам
	 * Category of operations for turnovers
	 * 
	 *
	 * @var string
	 */
	 public $operationTypeCategory = null;

	/**
	 * Если categoryDetails=true, то в ответе делается группировка по категориям операций
	 * If flag is switched on, turnovers will be grouped by its category
	 * 
	 *
	 * @var boolean
	 */
	 public $categoryDetails = null;

	/**
	 * Дополнительные атрибуты запроса
	 * Additional request parameters
	 * 
	 *
	 * @var KeyValueAttribute
	 */
	 public $attribute = null;

	/**
	 * Дополнительные атрибуты запроса
	 * Additional request parameters
	 * 
	 *
	 * @param KeyValueAttribute
	 *
	 * @return void
	 */
	public function addAttribute(KeyValueAttribute $item)
	{
		$this->attribute[] = $item;
	}

}
?>