<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * 
 */
class GetTurnoverListResponseTurnover
{
	
	/**
	 * Дата.
	 * Date.
	 * 
	 *
	 * @var date
	 */
	 public $date = null;

	/**
	 * Счет.
	 * Account.
	 * 
	 *
	 * @var string
	 */
	 public $account = null;

	/**
	 * Валюта.
	 * Currency.
	 * 
	 *
	 * @var string
	 */
	 public $currency = null;

	/**
	 * Категория операций (возвращается, если в запросе categoryDetails=true).
	 * Transaction category (if categoryDetails=true in the request).
	 * 
	 *
	 * @var string
	 */
	 public $operationTypeCategory = null;

	/**
	 * Приход. Сумма.
	 * Amount of income.
	 * 
	 *
	 * @var decimal
	 */
	 public $incomeAmount = null;

	/**
	 * Приход. Комиссия.
	 * Income commission fee.
	 * 
	 *
	 * @var decimal
	 */
	 public $incomeCommission = null;

	/**
	 * Приход. Количество.
	 * Income. Number of transactions.
	 * 
	 *
	 * @var long
	 */
	 public $incomeTransactionsCount = null;

	/**
	 * Приход. Заблокированная сумма.
	 * Income. Locked balance.
	 * 
	 *
	 * @var decimal
	 */
	 public $incomeLockedBalance = null;

	/**
	 * Расход. Сумма.
	 * Amount of expenses.
	 * 
	 *
	 * @var decimal
	 */
	 public $expenseAmount = null;

	/**
	 * Расход. В том числе комиссия.
	 * Amount of expenses including the commission fee.
	 * 
	 *
	 * @var decimal
	 */
	 public $expensesIncludingCommission = null;

	/**
	 * Расход. Дополнительная комиссия.
	 * Expenses. Extra commission fee.
	 * 
	 *
	 * @var decimal
	 */
	 public $expensesExtraCommission = null;

	/**
	 * Расход. Количество.
	 * Expenses. Number of transactions.
	 * 
	 *
	 * @var long
	 */
	 public $expenseTransactionsCount = null;

	/**
	 * Расход. Заблокированная сумма.
	 * Expenses. Locked balance.
	 * 
	 *
	 * @var decimal
	 */
	 public $expenseLockedBalance = null;

	/**
	 * Итого.
	 * Total.
	 * 
	 *
	 * @var decimal
	 */
	 public $total = null;

	/**
	 * Входящий остаток.
	 * Opening balance.
	 * 
	 *
	 * @var decimal
	 */
	 public $openingBalance = null;

	/**
	 * Исходящий остаток.
	 * Closing balance.
	 * 
	 *
	 * @var decimal
	 */
	 public $closingBalance = null;

}
