<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Ответ на запрос информации об итогах по месяцам
	 * Turnovers information response
	 * 
 */
class GetTurnoverListResponse
{
	
	/**
	 * Если groupByCurrency=true, то в ответе делается группировка по валюте
	 * If flag is switched on, turnovers will be grouped by currency
	 * 
	 *
	 * @var boolean
	 */
	 public $groupByCurrency = null;

	/**
	 * 
	 *
	 * @var GetTurnoverListResponseTurnover
	 */
	 public $turnover = null;

	/**
	 * 
	 *
	 * @param GetTurnoverListResponseTurnover
	 *
	 * @return void
	 */
	public function addTurnover(GetTurnoverListResponseTurnover $item)
	{
		$this->turnover[] = $item;
	}

}
?>