<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Информация об URL
	 * URL information
	 * 
 */
class InfoUrl
{
	
	/**
	 * URL платежной системы
	 * URL of payment system
	 * 
	 *
	 * @var string
	 */
	 public $href = null;

	/**
	 * Представление URL платежной системы
	 * URL name of payment system
	 * 
	 *
	 * @var string
	 */
	 public $text = null;

}
