<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Расширенная информация об URL платежной системы.
	 * Fully information about URL of the payment system.
	 * 
 */
class InfoUrl
{
	
	/**
	 * URL платежной системы.
	 * URL of the payment system.
	 * 
	 *
	 * @var string
	 */
	 public $href = null;

	/**
	 * Представление URL платежной системы.
	 * URL name of the payment system.
	 * 
	 *
	 * @var string
	 */
	 public $text = null;

}
