<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Информация о тарифе
	 * Information on tariff
	 * 
 */
class InfoTariff
{
	
	/**
	 * Валюта счета плательщика для которого расчитывается лимит суммы операции.
	 * The payer's account currency for which the calculated limit of the transaction amount.
	 * 
	 *
	 * @var string
	 */
	 public $sourceRangeCurrency = null;

	/**
	 * Минимальная сумма для плательщика, допустимая в операции.
	 * The minimum amount to the payer that is permitted in operation.
	 * 
	 *
	 * @var decimal
	 */
	 public $sourceAmountMin = null;

	/**
	 * Максимальная сумма для плательщика, допустимая в операции.
	 * The maximum amount to the payer that is permitted in operation.
	 * 
	 *
	 * @var decimal
	 */
	 public $sourceAmountMax = null;

	/**
	 * Валюта счета получателя платежа для которого расчитывается лимит суммы операции.
	 * Payee account currency for which the calculated limit of the transaction amount.
	 * 
	 *
	 * @var string
	 */
	 public $targetRangeCurrency = null;

	/**
	 * Минимальная сумма для получателя платежа, допустимая в операции.
	 * The minimum amount to the payee that is permitted in operation.
	 * 
	 *
	 * @var decimal
	 */
	 public $targetAmountMin = null;

	/**
	 * Максимальная сумма для получателя платежа, допустимая в операции.
	 * The maximum amount to the payee that is permitted in operation.
	 * 
	 *
	 * @var decimal
	 */
	 public $targetAmountMax = null;

}
