<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Информация о тарифе
	 * Tariff Info
	 * 
 */
class InfoTariff
{
	
	/**
	 * 
	 *
	 * @var string
	 */
	 public $sourceRangeCurrency = null;

	/**
	 * 
	 *
	 * @var decimal
	 */
	 public $sourceAmountMin = null;

	/**
	 * 
	 *
	 * @var decimal
	 */
	 public $sourceAmountMax = null;

	/**
	 * 
	 *
	 * @var string
	 */
	 public $targetRangeCurrency = null;

	/**
	 * 
	 *
	 * @var decimal
	 */
	 public $targetAmountMin = null;

	/**
	 * 
	 *
	 * @var decimal
	 */
	 public $targetAmountMax = null;

}
