<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Выставление счета к оплате.
	 * Making new invoice (request for payment).
	 * 
 */
class InvoiceRequest extends InvoiceRequestType
{
	
}
?>