<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Тип, описывающий параметры операции для выставления счета к оплате.
	 * Transaction parameters type for making new invoice (request for payment).
	 * 
 */
class InvoiceRequestType
{
	
	/**
	 * Номер счета плательщика
	 * Payer account number
	 * 
	 *
	 * @var long
	 */
	 public $payer = null;

	/**
	 * Номер счета получателя
	 * Payee account number
	 * 
	 *
	 * @var long
	 */
	 public $payee = null;

	/**
	 * Сумма
	 * Amount
	 * 
	 *
	 * @var decimal
	 */
	 public $amount = null;

	/**
	 * Внешний номер операции
	 * external transaction identificator
	 * 
	 *
	 * @var string
	 */
	 public $clientTransaction = null;

	/**
	 * Описание операции
	 * Transaction description or comments
	 * 
	 *
	 * @var normalizedString
	 */
	 public $description = null;

	/**
	 * Произвольный параметр
	 * Custom parameter
	 * 
	 *
	 * @var string
	 */
	 public $mnt_custom1 = null;

	/**
	 * Произвольный параметр
	 * Custom parameter
	 * 
	 *
	 * @var string
	 */
	 public $mnt_custom2 = null;

	/**
	 * Произвольный параметр
	 * Custom parameter
	 * 
	 *
	 * @var string
	 */
	 public $mnt_custom3 = null;

	/**
	 * Набор полей, которые необходимо сохранить в качестве атрибутов операции. Значения дат в формате dd.MM.yyyy HH:mm:ss.
	 * Для того чтобы провести прямое дебетование, следует передать атрибут с ключом "SUBSCRIBERID" и в значении указать ID подписчика.
	 * Прямое дебетование будет проведено, если ID подписчика указано верно, если пользователь разрешил проводить прямое дебетование,
	 * если указанная сумма есть на балансе пользователя. В данном случае деньги будут списаны со счета пользователя, в ответе на запрос
	 * в поле Статус будет указано INPROGRESS, зачисление денег на счет получателя будет проведено в асинхронном режиме.
	 * Если прямое дебетование не может быть проведено или во время его выполнения произойдет ошибка,
	 * то инвойс будет создан и в ответе на запрос в поле Статус будет указано CREATED.
	 * Key-value pairs that will be saved as a transaction attributes. Use format dd.MM.yyyy HH:mm:ss for date values.
	 * To initiate direct debit you have to pass "SUBSCRIBERID" attribute with corresponding subscriber id in the value.
	 * The direct debit will be processed if subscriber id is specified, the direct debit processing is permitted by user and user has enough funds on his account.
	 * If the direct debit is processed successfully, user's account is debited, the transaction status reported in the response is INPROGRESS, crediting the payee's account starts asynchronously.
	 * If the direct debit can't be processed or an error occures during the processing, the invoice is left registered and the transaction status is CREATED.
	 * 
	 *
	 * @var OperationInfo
	 */
	 public $operationInfo = null;

}
?>