<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Выставление счета к оплате.
	 * Request parameters for creating an invoice.
	 * 
 */
class InvoiceRequest extends InvoiceRequestType
{
	
}
