<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на выставление счета к оплате.
	 * Response to a request for creating an invoice.
	 * 
 */
class InvoiceResponse extends TransactionResponseType
{
	
}
