<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Выставление счета к оплате в пакетном режиме.
	 * Making new invoice (request for payment) in batch processing mode.
	 * 
 */
class InvoiceBatchRequest extends InvoiceBatchRequestType
{
	
}
?>