<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Тип, который позволяет работать с сущностями типа "ключ-значение".
	 * Key-value pairs type.
	 * 
 */
class KeyValueAttribute
{
	
	/**
	 * 
	 *
	 * @var string
	 */
	 public $key = null;

	/**
	 * 
	 *
	 * @var string
	 */
	 public $value = null;

}
?>