<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Тип, который позволяет работать с сущностями типа "ключ-значение".
	 * Specifies additional attributes. Each attribute contains the key element, which specifies the name of the attribute, and the value element that specifies the value of the attribute.
	 * 
 */
class KeyValueAttribute
{
	
	/**
	 * 
	 *
	 * @var string
	 */
	 public $key = null;

	/**
	 * 
	 *
	 * @var string
	 */
	 public $value = null;

}
