<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;
/**
 * 
 */
class OperationStatusState
{

	/**
	 * Средства списаны
	 * Debited
	 * 
	 *
	 * @var string
	 */
	const DEBITED = 'DEBITED';

	/**
	 * Средства зачислены
	 * Credited
	 * 
	 *
	 * @var string
	 */
	const CREDITED = 'CREDITED';

	/**
	 * Выполнено
	 * Completed
	 * 
	 *
	 * @var string
	 */
	const COMPLETED = 'COMPLETED';

	/**
	 * Заморожено
	 * Frozen
	 * 
	 *
	 * @var string
	 */
	const FROZEN = 'FROZEN';

	/**
	 * Отменено
	 * Cancelled
	 * 
	 *
	 * @var string
	 */
	const CANCELED = 'CANCELED';

}
?>