<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Информация о сумме операции в шаблоне.
	 * 
 */
class OperationTemplateAmountInfo extends AbstractAttributeObject
{
	
	/**
	 * Тип суммы в шаблоне операции.
	 * 
	 *
	 * @var string
	 */
	 public $type = null;

}
