<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Тип, описывающий атрибуты операции в ответах в пакетном запросе.
	 * Transaction attributes for responses in batch mode.
	 * 
 */
class OperationInfoBatchResponseType
{
	
}
