<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Информация о времени выполнения шаблона.
	 * 
 */
class OperationTemplateTimeInfo extends AbstractAttributeObject
{
	
	/**
	 * Периодичность выполнения шаблона.
	 * 
	 *
	 * @var string
	 */
	 public $type = null;

	/**
	 * Начало работы шаблона.
	 * Время, которое здесь указывается, должно быть кратно часу. Если будут указаны минуты, то они будут "обрезаны".
	 * Например, если указать, что время выполнения шаблона каждый день в 13:29, то шаблон будет выполняться каждый день в 13:00.
	 * Время, которое здесь указывается, должно быть больше текущего времени.
	 * 
	 *
	 * @var dateTime
	 */
	 public $startDateTime = null;

	/**
	 * Дата и время окончания работы шаблона. Необязательное поле.
	 * 
	 *
	 * @var dateTime
	 */
	 public $endDateTime = null;

}
