<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;
/**
 * 
 */
class OperationTypeCategory
{

	/**
	 * Ввод средств
	 * Deposit
	 * 
	 *
	 * @var string
	 */
	const DEPOSIT = 'DEPOSIT';

	/**
	 * Вывод средств
	 * Withdrawal
	 * 
	 *
	 * @var string
	 */
	const WITHDRAWAL = 'WITHDRAWAL';

	/**
	 * Внутренний перевод
	 * Transfer
	 * 
	 *
	 * @var string
	 */
	const TRANSFER = 'TRANSFER';

	/**
	 * Товары и услуги
	 * Business
	 * 
	 *
	 * @var string
	 */
	const BUSINESS = 'BUSINESS';

}
?>