<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Тип, представляющий список операций.
	 * Содержит разбиение по страницам для отображения длинных списков.
	 * Transaction list type.
	 * Contains paged structure for long list presentation.
	 * 
 */
class OperationInfoList
{
	
	/**
	 * Количество операций, возвращаемых в результате запроса.
	 * Transaction per page within one request.
	 * 
	 *
	 * @var long
	 */
	 public $pageSize = null;

	/**
	 * Номер текущей страницы. Нумерация начинается с 1
	 * Current page number starting with 1.
	 * 
	 *
	 * @var long
	 */
	 public $pageNumber = null;

	/**
	 * Максимальное количество страниц с операциями по данному запросу
	 * Total page count for given request.
	 * 
	 *
	 * @var long
	 */
	 public $pagesCount = null;

	/**
	 * Количество операций на текущей странице.
	 * Меньше или равно pageSize.
	 * Последняя страница может содержать операций меньше, чем pageSize.
	 * Transactions count in current page.
	 * Less or equal to pageSize.
	 * Last page may contain less than pageSize transactions.
	 * 
	 *
	 * @var long
	 */
	 public $size = null;

	/**
	 * Общее количество операций, которое можно получить в данной
	 * выборке
	 * Total transactions count for given request.
	 * 
	 *
	 * @var long
	 */
	 public $totalSize = null;

	/**
	 * Список операций
	 * Transaction list
	 * 
	 *
	 * @var OperationInfo
	 */
	 public $operation = null;

	/**
	 * Список операций
	 * Transaction list
	 * 
	 *
	 * @param OperationInfo
	 *
	 * @return void
	 */
	public function addOperation(OperationInfo $item)
	{
		$this->operation[] = $item;
	}

}
?>