<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;
/**
 * Тип, описывающий статусы операций в системе МОНЕТА.РУ.
	 * Данный тип может иметь только определенные значения, описанные ниже.
	 * Transaction status type in MONETA.RU.
	 * This type may have enumerated values.
	 * 
 */
class OperationStatus
{

	/**
	 * В обработке
	 * Transaction processing is in progress
	 * 
	 *
	 * @var string
	 */
	const INPROGRESS = 'INPROGRESS';

	/**
	 * Операция обработана
	 * Transaction processing completed successfully
	 * 
	 *
	 * @var string
	 */
	const SUCCEED = 'SUCCEED';

	/**
	 * Операция отменена
	 * Transaction processing is canceled
	 * 
	 *
	 * @var string
	 */
	const CANCELED = 'CANCELED';

	/**
	 * Средства зачислены на счет получателя. Уведомление по операции не отправлено (или не принято)
	 * Funds are credited to payee's account. External notification is not sent (or not accepted)
	 * 
	 *
	 * @var string
	 */
	const TAKENIN_NOTSENT = 'TAKENIN_NOTSENT';

	/**
	 * Операция создана
	 * Transaction is registered
	 * 
	 *
	 * @var string
	 */
	const CREATED = 'CREATED';

}
?>