<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * 
 */
class OperationTemplateAmountRest extends AbstractAttributeObject
{
	
	/**
	 * Остаток баланса, который должен остаться на счете после выполнения шаблона операции.
	 * 
	 *
	 * @var decimal
	 */
	 public $amount = null;

}
