<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;
/**
 * Тип, описывающий статусы операций в системе МОНЕТА.РУ. Данный тип может иметь только определенные значения, описанные ниже.
	 * The status of a transaction in MONETA.RU.
	 * 
 */
class OperationStatus
{

	/**
	 * В обработке.
	 * MONETA.RU is processing the transaction.
	 * 
	 *
	 * @var string
	 */
	const INPROGRESS = 'INPROGRESS';

	/**
	 * Операция обработана.
	 * Transaction processing completed successfully.
	 * 
	 *
	 * @var string
	 */
	const SUCCEED = 'SUCCEED';

	/**
	 * Операция отменена.
	 * Transaction has been canceled.
	 * 
	 *
	 * @var string
	 */
	const CANCELED = 'CANCELED';

	/**
	 * Средства зачислены на счет получателя. Уведомление по операции не отправлено (или не принято).
	 * The funds are credited to the payee's account. MONETA.RU did not send the processed payment report or you did not return a plain text response to the report.
	 * 
	 *
	 * @var string
	 */
	const TAKENIN_NOTSENT = 'TAKENIN_NOTSENT';

	/**
	 * Операция создана.
	 * Transaction is registered in MONETA.RU.
	 * 
	 *
	 * @var string
	 */
	const CREATED = 'CREATED';

	/**
	 * Операция заморожена.
	 * Transaction is frozen.
	 * 
	 *
	 * @var string
	 */
	const FROZEN = 'FROZEN';

	/**
	 * Средства списаны.
	 * Debited.
	 * 
	 *
	 * @var string
	 */
	const TAKENOUT = 'TAKENOUT';

}
