<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Напоминание о выполнении регулярного шаблона.
	 * Если в разделе "Мой счет" - "Персональные данные" - "Уведомления", добавить уведомление с флагом "Регулярные платежи",
	 * то можно получать напоминания о начале выполения шаблона.
	 * 
 */
class OperationTemplateReminderInfo extends AbstractAttributeObject
{
	
	/**
	 * true - отсылать напоминания.
	 * false - не отсылать напоминания.
	 * 
	 *
	 * @var boolean
	 */
	 public $remind = null;

	/**
	 * За сколько часов до выполнения шаблона высылать напоминание.
	 * 
	 *
	 * @var int
	 */
	 public $hoursBeforeExecution = null;

	/**
	 * Список уведомлений, куда уходят напоминания. Только для чтения.
	 * 
	 *
	 * @var AbstractAttributeObject
	 */
	 public $notification = null;

}
