<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * 
 */
class OperationTemplateAmountRange extends AbstractAttributeObject
{
	
	/**
	 * Минимальное значение баланса на счете списания.
	 * 
	 *
	 * @var decimal
	 */
	 public $amountMinValue = null;

	/**
	 * Максимальное значение баланса на счете списания.
	 * 
	 *
	 * @var decimal
	 */
	 public $amountMaxValue = null;

}
