<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;
/**
 * Тип операции.
	 * Amount type.
	 * 
 */
class OperationAmountType
{

	/**
	 * Приход
	 * Income
	 * 
	 *
	 * @var string
	 */
	const INCOME = 'INCOME';

	/**
	 * Расход
	 * Expense
	 * 
	 *
	 * @var string
	 */
	const EXPENSE = 'EXPENSE';

}
