<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;
/**
 * Тип шаблона операции.
	 * Operation template type.
	 * 
 */
class OperationTemplateType
{

	/**
	 * Шаблон операции не будет выполняться на регулярной основе. Для таких шаблонов нельзя указать время выполнения. Шаблон можно выполнить только вручную.
	 * При создании такого типа шаблонов, необходимо указать элемент commonParameters.
	 * 
	 *
	 * @var string
	 */
	const COMMON = 'COMMON';

	/**
	 * Шаблон операции будет выполняться автоматически в указанное время.
	 * При создании такого типа шаблонов, необходимо указать элемент regularParameters.
	 * 
	 *
	 * @var string
	 */
	const REGULAR = 'REGULAR';

	/**
	 * Шаблоны прямого дебетования. Такие типы шаблонов только для чтения. Их нельзя создать через MONETA.MerchantAPI.
	 * 
	 *
	 * @var string
	 */
	const DIRECT_DEBIT = 'DIRECT_DEBIT';

}
