<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;
/**
 * 
 */
class OperationStatusState
{

	/**
	 * Средства списаны
	 * Debited
	 * 
	 *
	 * @var string
	 */
	const DEBITED = 'DEBITED';

	/**
	 * Средства зачислены
	 * Credited
	 * 
	 *
	 * @var string
	 */
	const CREDITED = 'CREDITED';

	/**
	 * Выполнено
	 * Completed
	 * 
	 *
	 * @var string
	 */
	const COMPLETED = 'COMPLETED';

}
?>