<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Тип, позволяющий задать необходимую страницу при отображении длинных списков.
	 * Long list retrieval type.
	 * 
 */
class Pager
{
	
	/**
	 * Номер страницы, которую нужно получить. Минимальное значение равно 1.
	 * Значение по умолчанию равно 1.
	 * Page number to retrieve. Minimal value is 1.
	 * By default is 1.
	 * 
	 *
	 * @var int
	 */
	 public $pageNumber = null;

	/**
	 * Сколько записей необходимо получить на одной странице. Минимальное
	 * значение равно 1. Максимальное значение равно 100. Значение по умолчанию равно 10.
	 * Transactions per page. Minimal value is 1.
	 * Maximal value is 100.
	 * By default is 10.
	 * 
	 *
	 * @var int
	 */
	 public $pageSize = null;

}
?>