<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Тип, позволяющий задать необходимую страницу при отображении длинных списков.
	 * Specifies paginating parameters for a long list of MONETA.RU objects, such as transactions or users.
	 * 
 */
class Pager
{
	
	/**
	 * Номер страницы, которую нужно получить.
	 * Минимальное значение равно 1.
	 * Значение по умолчанию равно 1.
	 * Specifies the number of the page that you want to get.
	 * Minimum value: 1.
	 * Default value: 1.
	 * 
	 *
	 * @var int
	 */
	 public $pageNumber = null;

	/**
	 * Сколько записей необходимо получить на одной странице.
	 * Минимальное значение равно 1.
	 * Максимальное значение равно 1000.
	 * Значение по умолчанию равно 25.
	 * Specifies the maximum number of transactions per page.
	 * Valid range: 1-1000.
	 * Default value: 25.
	 * 
	 *
	 * @var int
	 */
	 public $pageSize = null;

}
