<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Информация о платежной системе
	 * Payment system info
	 * 
 */
class PaymentSystemInfoComplexType
{
	
	/**
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

	/**
	 * 
	 *
	 * @var string
	 */
	 public $name = null;

	/**
	 * 
	 *
	 * @var string
	 */
	 public $icon = null;

	/**
	 * 
	 *
	 * @var int
	 */
	 public $logicalGroup = null;

	/**
	 * 
	 *
	 * @var InfoUrl
	 */
	 public $infoUrl = null;

	/**
	 * 
	 *
	 * @var ReferenceData
	 */
	 public $referenceData = null;

	/**
	 * 
	 *
	 * @var InfoTariff
	 */
	 public $infoTariff = null;

	/**
	 * 
	 *
	 * @var string
	 */
	 public $currencies = null;

	/**
	 * 
	 *
	 * @var string
	 */
	 public $key = null;

	/**
	 * 
	 *
	 * @var string
	 */
	 public $alias = null;

	/**
	 * 
	 *
	 * @var string
	 */
	 public $groupAlias = null;

}
