<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Результат информации об платежной системе.
	 * Response information about payment system
	 * 
 */
class PaymentSystemInfoResponse
{
	
	/**
	 * 
	 *
	 * @var PaymentSystemInfoComplexType
	 */
	 public $items = null;

	/**
	 * 
	 *
	 * @param PaymentSystemInfoComplexType
	 *
	 * @return void
	 */
	public function addItems(PaymentSystemInfoComplexType $item)
	{
		$this->items[] = $item;
	}

}
