<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Тип, описывающий представления информации о платежной системе.
	 * Type of present information of payment system
	 * 
 */
class PaymentSystemInfoComplexType
{
	
	/**
	 * ID пользователя в системе МОНЕТА.РУ.
	 * Unique identifier of the user in MONETA.RU.
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

	/**
	 * Наименование платежной системы.
	 * The name of payment system.
	 * 
	 *
	 * @var string
	 */
	 public $name = null;

	/**
	 * URL логотипа платежной системы.
	 * The URL of icon of the payment system.
	 * 
	 *
	 * @var string
	 */
	 public $icon = null;

	/**
	 * Наименование логической группы, к которой принадлежит платежная система.
	 * The name of logical group of the payment system.
	 * 
	 *
	 * @var string
	 */
	 public $logicalGroup = null;

	/**
	 * Расширенная информация об URL платежной системы.
	 * Fully information about URL of the payment system.
	 * 
	 *
	 * @var InfoUrl
	 */
	 public $infoUrl = null;

	/**
	 * Справочная информация о платежной системе.
	 * Reference information.
	 * 
	 *
	 * @var ReferenceData
	 */
	 public $referenceData = null;

	/**
	 * Краткая информация о тарифе.
	 * Short information on tariff.
	 * 
	 *
	 * @var InfoTariff
	 */
	 public $infoTariff = null;

	/**
	 * Список валюты счетов платежной системы. Располагаются в том же порядке, что и идентификаторы счетов в psAccountIds.
	 * List of currency payment system accounts. Are located in the same order, as well as accounts in psAccountIds are.
	 * 
	 *
	 * @var string
	 */
	 public $currencies = null;

	/**
	 * Список счетов платежной системы. Располагаются в том же порядке, что и валюты счетов в currencies.
	 * List of payment system accounts. Are located in the same order, as well as accounts currencies in currencies are.
	 * 
	 *
	 * @var string
	 */
	 public $psAccountIds = null;

}
