<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Персональные данные пользователя.
	 * Personal information.
	 * 
 */
class PersonalInformation
{
	
	/**
	 * 
	 *
	 * @var Profile
	 */
	 public $profile = null;

	/**
	 * 
	 *
	 * @var Document
	 */
	 public $document = null;

}
