<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * 
 */
class ProfileNotification extends AbstractAttributeObject
{
	
	/**
	 * Идентификатор уведомления.
	 * 
	 *
	 * @var long
	 */
	 public $id = null;

	/**
	 * Пользователь, которому принадлежат уведомления.
	 * The owner of the notifications.
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

	/**
	 * Тип уведомления.
	 * 
	 *
	 * @var string
	 */
	 public $type = null;

	/**
	 * Список получателей уведомлений.
	 * 
	 *
	 * @var string
	 */
	 public $recipient = null;

	/**
	 * Флаги уведомлений.
	 * 
	 *
	 * @var AbstractAttributeObject
	 */
	 public $flag = null;

	/**
	 * Флаги уведомлений.
	 * 
	 *
	 * @param AbstractAttributeObject
	 *
	 * @return void
	 */
	public function addFlag(AbstractAttributeObject $item)
	{
		$this->flag[] = $item;
	}

}
