<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * 
 */
class ProfileNotificationFlag extends AbstractAttributeObject
{
	
	/**
	 * Флаг уведомлений.
	 * 
	 *
	 * @var string
	 */
	 public $flag = null;

	/**
	 * true - флаг уведомлений установлен.
	 * false - флаг уведомлений не установлен.
	 * 
	 *
	 * @var boolean
	 */
	 public $enabled = null;

}
