<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * 
 */
class ProfileNotificationSelection extends ProfileNotification
{
	
	/**
	 * Выбрано данное уведомление или нет.
	 * 
	 *
	 * @var boolean
	 */
	 public $selected = null;

}
