<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Справочная информация о платежной системе.
	 * Reference information.
	 * 
 */
class ReferenceData
{
	
	/**
	 * Срок проведения банковской операции.
	 * The term of carrying out banking transactions.
	 * 
	 *
	 * @var string
	 */
	 public $period = null;

	/**
	 * Комиссия в процентах.
	 * The сommission, in percent.
	 * 
	 *
	 * @var string
	 */
	 public $percentage = null;

	/**
	 * Внешняя комиссия в процентах.
	 * The external сommission, in percent.
	 * 
	 *
	 * @var string
	 */
	 public $percentageExt = null;

	/**
	 * Комиcсия с плательщика (сумма).
	 * The commission payeer (amount).
	 * 
	 *
	 * @var decimal
	 */
	 public $sourceFee = null;

	/**
	 * Внешняя комиcсия с плательщика (сумма).
	 * External commission from the payer (amount).
	 * 
	 *
	 * @var decimal
	 */
	 public $sourceFeeExt = null;

	/**
	 * Комиcсия с получателя платежа (сумма).
	 * Commission to the payee (amount).
	 * 
	 *
	 * @var decimal
	 */
	 public $targetFee = null;

	/**
	 * Внешняя комиcсия с получателя платежа (сумма).
	 * External сommission to the payee (amount).
	 * 
	 *
	 * @var decimal
	 */
	 public $targetFeeExt = null;

}
