<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ по запросу возврата средств, содержащий информацию по возвратной операции.
	 * Response to a refund request.
	 * 
 */
class RefundResponse extends OperationInfo
{
	
}
