<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Ответ по запросу возврата средств, содержащий информацию по возвратной операции.
	 * Response containing refund transaction information.
	 * 
 */
class RefundResponse extends OperationInfo
{
	
}
?>