<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Параметры шаблона операции, если он имеет тип OperationTemplateType.REGULAR.
	 * 
 */
class RegularOperationTemplateParameters extends AbstractAttributeObject
{
	
	/**
	 * Информация о сумме операции в шаблоне.
	 * Этот элемент следует обязательно передавать при создании нового шаблона или шаблона из проведенной операции.
	 * Если шаблон редактируется, то этот элемент необязателен.
	 * 
	 *
	 * @var AbstractAttributeObject
	 */
	 public $amountInfo = null;

	/**
	 * Информация о времени выполнения шаблона.
	 * Этот элемент следует обязательно передавать при создании нового шаблона или шаблона из проведенной операции.
	 * Если шаблон редактируется, то этот элемент необязателен.
	 * 
	 *
	 * @var AbstractAttributeObject
	 */
	 public $timeInfo = null;

	/**
	 * Напоминание о выполнении регулярного шаблона.
	 * 
	 *
	 * @var AbstractAttributeObject
	 */
	 public $reminderInfo = null;

	/**
	 * Список e-mail уведомлений. Уведомления могут иметь только тип ProfileNotificationType.EMAIL.
	 * Уведомления используются только:
	 * При выводе в банк.
	 * Если сумма имеет тип (regularParameters.amountInfo.type):
	 * OperationTemplateAmountInfoType.PAYMENTS
	 * OperationTemplateAmountInfoType.CREDIT
	 * В этом случае, на указанные уведомления, будет приходит список операций, которые вошли в период вывода.
	 * Для указания уведомлений (при создании или редактировании шаблона), следует передать id уведомления
	 * и поле selected = true.
	 * 
	 *
	 * @var AbstractAttributeObject
	 */
	 public $operationsReportNotifications = null;

}
