<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Отчет без указания конкретной даты.
	 * Report.
	 * 
 */
class Report
{
	
	/**
	 * ID отчета.
	 * Report ID.
	 * 
	 *
	 * @var long
	 */
	 public $id = null;

	/**
	 * Название отчета.
	 * Report name.
	 * 
	 *
	 * @var string
	 */
	 public $name = null;

	/**
	 * ID пользователя в системе МОНЕТА.РУ.
	 * User ID.
	 * 
	 *
	 * @var long
	 */
	 public $unitId = null;

	/**
	 * Тип отчета.
	 * Пока имеет одно значение: 3.
	 * Report type ID.
	 * 
	 *
	 * @var long
	 */
	 public $typeId = null;

	/**
	 * Список экземпляров отчета.
	 * Report instances list.
	 * 
	 *
	 * @var ReportInstance
	 */
	 public $reportInstance = null;

	/**
	 * Список экземпляров отчета.
	 * Report instances list.
	 * 
	 *
	 * @param ReportInstance
	 *
	 * @return void
	 */
	public function addReportInstance(ReportInstance $item)
	{
		$this->reportInstance[] = $item;
	}

	/**
	 * 
	 *
	 * @var KeyValueAttribute
	 */
	 public $attribute = null;

	/**
	 * 
	 *
	 * @param KeyValueAttribute
	 *
	 * @return void
	 */
	public function addAttribute(KeyValueAttribute $item)
	{
		$this->attribute[] = $item;
	}

}
