<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Запрос на сохранение делегированного доступа к счету.
	 * Request for saving detailed information of delegated access.
	 * 
 */
class SaveAccountRelationRequest extends AccountRelation
{
	
	/**
	 * Платежный пароль.
	 * Payment password for account.
	 * 
	 *
	 * @var normalizedString
	 */
	 public $paymentPassword = null;

	/**
	 * Запрос для платежного пароля
	 * Payment password challenge
	 * 
	 *
	 * @var string
	 */
	 public $paymentPasswordChallenge = null;

}
?>