<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на получение статуса SECURETOKEN.
	 * SECURETOKEN status request.
	 * 
 */
class SecureDataStatusRequest
{
	
	/**
	 * Secure Token.
	 * Secure Token.
	 * 
	 *
	 * @var string
	 */
	 public $secureToken = null;

}
