<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос SecureDataRequest.
	 * Response to SecureDataRequest.
	 * 
 */
class SecureDataResponse
{
	
	/**
	 * Secure Token.
	 * Secure Token.
	 * 
	 *
	 * @var string
	 */
	 public $secureToken = null;

	/**
	 * Срок действия Secure Token.
	 * Secure token expiration date.
	 * 
	 *
	 * @var dateTime
	 */
	 public $expirationDate = null;

}
