<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос SecureDataStatusRequest.
	 * Response to SecureDataStatusRequest.
	 * 
 */
class SecureDataStatusResponse
{
	
	/**
	 * Срок действия Secure Token.
	 * Secure token expiration date.
	 * 
	 *
	 * @var dateTime
	 */
	 public $expirationDate = null;

	/**
	 * Свойства, которые могут вернуться в ответе. Сохраненных свойств может быть больше, но возвращаются только эти:
	 * CARDNUMBER. Маскированное значение.
	 * CARDEXPIRATION
	 * CARDHOLDER
	 * PAYEECARDNUMBER. Маскированное значение.
	 * Saved attributes:
	 * CARDNUMBER. Masked value.
	 * CARDEXPIRATION
	 * CARDHOLDER
	 * PAYEECARDNUMBER. Masked value.
	 * 
	 *
	 * @var KeyValueAttribute
	 */
	 public $attribute = null;

	/**
	 * Свойства, которые могут вернуться в ответе. Сохраненных свойств может быть больше, но возвращаются только эти:
	 * CARDNUMBER. Маскированное значение.
	 * CARDEXPIRATION
	 * CARDHOLDER
	 * PAYEECARDNUMBER. Маскированное значение.
	 * Saved attributes:
	 * CARDNUMBER. Masked value.
	 * CARDEXPIRATION
	 * CARDHOLDER
	 * PAYEECARDNUMBER. Masked value.
	 * 
	 *
	 * @param KeyValueAttribute
	 *
	 * @return void
	 */
	public function addAttribute(KeyValueAttribute $item)
	{
		$this->attribute[] = $item;
	}

}
