<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ, который приходит на запрос SimplifiedIdentificationRequest.
	 * Response to SimplifiedIdentificationRequest.
	 * 
 */
class SimplifiedIdentificationResponse extends AbstractAttributeObject
{
	
	/**
	 * true. Упрощённая идентификация проведена успешно.
	 * false. Упрощённая идентификация не была проведена.
	 * true. Simplified identification completed successfully.
	 * false. Simplified identification failed.
	 * 
	 *
	 * @var boolean
	 */
	 public $success = null;

	/**
	 * Поле содержит описание ошибки, если Упрощённая идентификация не была проведена.
	 * Если Упрощённая идентификация проведена успешно, то поле error пустое.
	 * If an error occurs when processing a simplified identification, the error element contains an error description.
	 * If the simplified identification completes successfully, the error element is empty.
	 * 
	 *
	 * @var string
	 */
	 public $error = null;

	/**
	 * Поле содержит код ошибки, если Упрощённая идентификация не была проведена.
	 * Если Упрощённая идентификация проведена успешно, то поле errorCode пустое.
	 * Коды ошибок совпадают со значением элемента faultDetail (смотрите описание для этого элемента).
	 * If an error occurs when processing a simplified identification, the errorCode element contains an error code.
	 * See the faultDetail element for the error code descriptions.
	 * 
	 *
	 * @var string
	 */
	 public $errorCode = null;

	/**
	 * Текущие персональные данные пользователя.
	 * В profile возвращаются следующие поля:
	 * first_name
	 * middle_initial_name
	 * last_name
	 * cell_phone
	 * snils
	 * inn (optional)
	 * В document возвращаются следующие поля:
	 * type
	 * series
	 * number
	 * issuer
	 * issued
	 * department
	 * Current personal information.
	 * User information contains the following attributes:
	 * first_name
	 * middle_initial_name
	 * last_name
	 * cell_phone
	 * snils
	 * inn (optional)
	 * The document contains the following attributes:
	 * type (PASSPORT)
	 * series
	 * number
	 * issuer
	 * issued
	 * department
	 * 
	 *
	 * @var PersonalInformation
	 */
	 public $personalInformation = null;

}
