<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на перевод денежных средств в пакетном режиме.
	 * Request for multiple money transfer operations in batch mode.
	 * 
 */
class TransferBatchRequest extends TransactionBatchRequestType
{
	
}
