<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Тип, описывающий атрибуты операции в ответах.
	 * Transaction attributes type for responses.
	 * 
 */
class TransactionResponseType
{
	
	/**
	 * Текущий статус операции
	 * Current transaction status
	 * 
	 *
	 * @var string
	 */
	 public $status = null;

	/**
	 * Время последней модификации операции
	 * Transaction modification timestamp
	 * 
	 *
	 * @var dateTime
	 */
	 public $dateTime = null;

	/**
	 * Номер операции
	 * Transaction ID in MONETA.RU
	 * 
	 *
	 * @var long
	 */
	 public $transaction = null;

	/**
	 * Внешний номер операции
	 * External transaction ID
	 * 
	 *
	 * @var string
	 */
	 public $clientTransaction = null;

}
?>