<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос на перевод денежных средств.
	 * Request for transferring money to another account.
	 * 
 */
class TransferRequest extends TransactionRequestType
{
	
}
