<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос перевода денежных средств.
	 * Response to a request for transferring money to another account.
	 * 
 */
class TransferResponse extends TransactionResponseType
{
	
}
