<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Ответ на запрос создания/редактирования файла документа
	 * Если в процессе сохранения файла произошла ошибка, то возникнет Exception.
	 * Если Exception не возник - значит файл гарантированно сохранен.
	 * Response for file adding/modification.
	 * Response contains no data unless some error has occured while modification.
	 * If reponse has no Exception then file is uploaded successfully.
	 * 
 */
class UploadProfileDocumentFileResponse
{
	
}
?>