<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1393417765 


namespace Moneta\Types;

/**
 * Запрос на создание/редактирование файла документа
	 * Request for file adding/modification.
	 * 
 */
class UploadProfileDocumentFileRequest
{
	
	/**
	 * Если указано поле fileId - файл редактируется, иначе создается новый файл.
	 * Поле approved в данном запросе не используется.
	 * Если не указан mimeType, но в запросе есть имя файла (поле title), то mimeType будет вычисляться по расширению файла
	 * Specify "fileId" to modify file, omit "fileId" to add new file.
	 * Approved is not used.
	 * If "mimeType" omitted and "title" is specified, "mimeType" will be resolved by filename extension.
	 * 
	 *
	 * @var File
	 */
	 public $file = null;

}
?>