<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Ответ на запрос проверки проведения операции в системе МОНЕТА.РУ
	 * Transaction verification response.
	 * 
 */
class VerifyTransactionResponseType extends VerifyTransferResponseType
{
	
	/**
	 * Идентификатор операции в системе МОНЕТА.РУ.
	 * The identifier of transaction.
	 * 
	 *
	 * @var long
	 */
	 public $transactionId = null;

	/**
	 * Статус операции в системе МОНЕТА.РУ.
	 * Transaction status type in MONETA.RU
	 * 
	 *
	 * @var string
	 */
	 public $operationStatus = null;

}
?>