<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Тип, описывающий состояние операции в системе МОНЕТА.РУ
	 * Type describes verification status of transaction.
	 * 
 */
class VerifyTransferResponseType
{
	
	/**
	 * Если поле равно true, то данная операция может
	 * быть проведена в системе МОНЕТА.РУ
	 * If true the transaction may be processed in MONETA.RU
	 * 
	 *
	 * @var boolean
	 */
	 public $isTransactionValid = null;

	/**
	 * Описание текущего статуса операции.
	 * Description of current transaction status.
	 * 
	 *
	 * @var string
	 */
	 public $description = null;

	/**
	 * Если операция может быть проведена, то в данном поле содержатся детали операции.
	 * Иначе - это поле пустое.
	 * Additional information if transaction may be processed. Otherwise empty.
	 * 
	 *
	 * @var ForecastTransactionResponseType
	 */
	 public $forecast = null;

	/**
	 * Поле содержит код ошибки. Поле заполнено только тогда, когда есть описание ошибки в поле description.
	 * Для получения этого поля в запросе необходимо выставлять атрибут version равный или больше VERSION_2.
	 * Коды ошибок совпадают со значением элемента faultDetail (смотрите описание для этого элемента).
	 * The field contains error code. The field "errorCode" is specified if the field "description" is present and contains error description.
	 * For retrieving errorCode the request attribute "version" has to be set to "VERSION_2" or greater.
	 * Error codes values correspond to "faultDetail" description.
	 * 
	 *
	 * @var string
	 */
	 public $errorCode = null;

	/**
	 * Дополнительные свойства операции.
	 * Для получения этого поля в запросе необходимо выставлять атрибут version равный или больше VERSION_2.
	 * Если в ответе придет поле с ключом key="paymentPasswordChallengeRequired" и значением value="true", то перед проведением операции следует сделать запрос "GetAccountPaymentPasswordChallengeRequest", который вернет строку запроса для платежного пароля. Это значение необходимо использовать в поле "paymentPasswordChallenge" в запросах на проведение операции (например: "PaymentRequest", "TransferRequest", "AuthoriseTransactionRequest" и т.д.).
	 * Additional transaction details.
	 * For retrieving operationInfo the request attribute "version" has to be set to "VERSION_2" or greater.
	 * If the response contains an attribute with the key="paymentPasswordChallengeRequired" and value="true", you have to call "GetAccountPaymentPasswordChallengeRequest" for payer's account to retrieve "paymentPasswordChallenge", which is used within financial processing requests such as
	 * "PaymentRequest", "TransferRequest", "AuthoriseTransactionRequest".
	 * 
	 *
	 * @var OperationInfo
	 */
	 public $operationInfo = null;

}
?>