<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 
// Timestamp: 1364986803 


namespace Moneta\Types;

/**
 * Запрос возможности провести операцию в системе МОНЕТА.РУ.
	 * Transaction verification request.
	 * 
 */
class VerifyTransferRequest extends TransactionRequestType
{
	
}
?>