<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Ответ на запрос проверки проведения операции в системе MONETA.RU.
	 * Response to a request for verifying a transaction in MONETA.RU.
	 * 
 */
class VerifyTransactionResponse extends VerifyTransactionResponseType
{
	
}
