<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;

/**
 * Запрос возможности провести операцию в системе MONETA.RU. Запрос выполняется в пакетном режиме.
	 * Transaction validation request. Request in batch mode.
	 * 
 */
class VerifyPaymentBatchRequest extends PaymentBatchRequestType
{
	
}
