<?php

// Warning! This code was generated by WSDL2PHP tool. 
// author: Filippov Andrey <afi.work@gmail.com> 
// see https://solo-framework-lib.googlecode.com 

namespace Moneta\Types;
/**
 * Список версий, который используется в MONETA.MerchantAPI. Если функциональность зависит от конкретной версии, то в описании запроса это будет указано дополнительно.
	 * Если версия не указана, то по умолчанию используется VERSION_1.
	 * Defines the MONETA.Merchant API version. Differences between versions, if any, are described in the documentation.
	 * Default value: VERSION_1.
	 * 
 */
class Version
{

	/**
	 * 
	 *
	 * @var string
	 */
	const VersionVERSION_1 = 'VERSION_1';

	/**
	 * 
	 *
	 * @var string
	 */
	const VersionVERSION_2 = 'VERSION_2';

	/**
	 * 
	 *
	 * @var string
	 */
	const VersionVERSION_3 = 'VERSION_3';

	/**
	 * 
	 *
	 * @var string
	 */
	const VersionVERSION_4 = 'VERSION_4';

	/**
	 * 
	 *
	 * @var string
	 */
	const VersionVERSION_5 = 'VERSION_5';

}
